/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  try {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  } catch (e) {
    throw mod = 0, e;
  }
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// node_modules/papaparse/papaparse.min.js
var require_papaparse_min = __commonJS({
  "node_modules/papaparse/papaparse.min.js"(exports, module2) {
    ((e, t) => {
      "function" == typeof define && define.amd ? define([], t) : "object" == typeof module2 && "undefined" != typeof exports ? module2.exports = t() : e.Papa = t();
    })(exports, function r() {
      var n = "undefined" != typeof self ? self : "undefined" != typeof window ? window : void 0 !== n ? n : {};
      var d, s = !n.document && !!n.postMessage, a = n.IS_PAPA_WORKER || false, o = {}, h = 0, v = {};
      function P(e) {
        return 65279 === e.charCodeAt(0) ? e.slice(1) : e;
      }
      function u(e) {
        this._handle = null, this._finished = false, this._completed = false, this._halted = false, this._input = null, this._baseIndex = 0, this._partialLine = "", this._rowCount = 0, this._start = 0, this._nextChunk = null, this.isFirstChunk = true, this._completeResults = { data: [], errors: [], meta: {} }, function(e2) {
          var t = b(e2);
          t.chunkSize = parseInt(t.chunkSize), e2.step || e2.chunk || (t.chunkSize = null);
          this._handle = new i(t), (this._handle.streamer = this)._config = t;
        }.call(this, e), this.parseChunk = function(t, e2) {
          var i2 = parseInt(this._config.skipFirstNLines) || 0;
          if (this.isFirstChunk && 0 < i2) {
            let e3 = this._config.newline;
            e3 || (r2 = this._config.quoteChar || '"', e3 = this._handle.guessLineEndings(t, r2)), t = [...t.split(e3).slice(i2)].join(e3);
          }
          this.isFirstChunk && q(this._config.beforeFirstChunk) && void 0 !== (r2 = this._config.beforeFirstChunk(t)) && (t = r2), this.isFirstChunk = false, this._halted = false;
          var i2 = this._partialLine + t, r2 = (this._partialLine = "", this._handle.parse(i2, this._baseIndex, !this._finished));
          if (!this._handle.paused() && !this._handle.aborted()) {
            t = r2.meta.cursor, i2 = (this._finished || (this._partialLine = i2.substring(t - this._baseIndex), this._baseIndex = t), r2 && r2.data && (this._rowCount += r2.data.length), this._finished || this._config.preview && this._rowCount >= this._config.preview);
            if (a) n.postMessage({ results: r2, workerId: v.WORKER_ID, finished: i2 });
            else if (q(this._config.chunk) && !e2) {
              if (this._config.chunk(r2, this._handle), this._handle.paused() || this._handle.aborted()) return void (this._halted = true);
              this._completeResults = r2 = void 0;
            }
            return this._config.step || this._config.chunk || (this._completeResults.data = this._completeResults.data.concat(r2.data), this._completeResults.errors = this._completeResults.errors.concat(r2.errors), this._completeResults.meta = r2.meta), this._completed || !i2 || !q(this._config.complete) || r2 && r2.meta.aborted || (this._config.complete(this._completeResults, this._input), this._completed = true), i2 || r2 && r2.meta.paused || this._nextChunk(), r2;
          }
          this._halted = true;
        }, this._sendError = function(e2) {
          q(this._config.error) ? this._config.error(e2) : a && this._config.error && n.postMessage({ workerId: v.WORKER_ID, error: e2, finished: false });
        };
      }
      function f(e) {
        var r2;
        (e = e || {}).chunkSize || (e.chunkSize = v.RemoteChunkSize), u.call(this, e), this._nextChunk = s ? function() {
          this._readChunk(), this._chunkLoaded();
        } : function() {
          this._readChunk();
        }, this.stream = function(e2) {
          this._input = e2, this._nextChunk();
        }, this._readChunk = function() {
          if (this._finished) this._chunkLoaded();
          else {
            if (r2 = new XMLHttpRequest(), this._config.withCredentials && (r2.withCredentials = this._config.withCredentials), s || (r2.onload = y(this._chunkLoaded, this), r2.onerror = y(this._chunkError, this)), r2.open(this._config.downloadRequestBody ? "POST" : "GET", this._input, !s), this._config.downloadRequestHeaders) {
              var e2, t = this._config.downloadRequestHeaders;
              for (e2 in t) r2.setRequestHeader(e2, t[e2]);
            }
            var i2;
            this._config.chunkSize && (i2 = this._start + this._config.chunkSize - 1, r2.setRequestHeader("Range", "bytes=" + this._start + "-" + i2));
            try {
              r2.send(this._config.downloadRequestBody);
            } catch (e3) {
              this._chunkError(e3.message);
            }
            s && 0 === r2.status && this._chunkError();
          }
        }, this._chunkLoaded = function() {
          4 === r2.readyState && (r2.status < 200 || 400 <= r2.status ? this._chunkError() : (this._start += this._config.chunkSize || r2.responseText.length, this._finished = !this._config.chunkSize || this._start >= ((e2) => null !== (e2 = e2.getResponseHeader("Content-Range")) ? parseInt(e2.substring(e2.lastIndexOf("/") + 1)) : -1)(r2), this.parseChunk(r2.responseText)));
        }, this._chunkError = function(e2) {
          e2 = r2.statusText || e2;
          this._sendError(new Error(e2));
        };
      }
      function l(e) {
        (e = e || {}).chunkSize || (e.chunkSize = v.LocalChunkSize), u.call(this, e);
        var i2, r2, n2 = "undefined" != typeof FileReader;
        this.stream = function(e2) {
          this._input = e2, r2 = e2.slice || e2.webkitSlice || e2.mozSlice, n2 ? ((i2 = new FileReader()).onload = y(this._chunkLoaded, this), i2.onerror = y(this._chunkError, this)) : i2 = new FileReaderSync(), this._nextChunk();
        }, this._nextChunk = function() {
          this._finished || this._config.preview && !(this._rowCount < this._config.preview) || this._readChunk();
        }, this._readChunk = function() {
          var e2 = this._input, t = (this._config.chunkSize && (t = Math.min(this._start + this._config.chunkSize, this._input.size), e2 = r2.call(e2, this._start, t)), i2.readAsText(e2, this._config.encoding));
          n2 || this._chunkLoaded({ target: { result: t } });
        }, this._chunkLoaded = function(e2) {
          this._start += this._config.chunkSize, this._finished = !this._config.chunkSize || this._start >= this._input.size, this.parseChunk(e2.target.result);
        }, this._chunkError = function() {
          this._sendError(i2.error);
        };
      }
      function c(e) {
        var i2;
        u.call(this, e = e || {}), this.stream = function(e2) {
          return i2 = e2, this._nextChunk();
        }, this._nextChunk = function() {
          var e2, t;
          if (!this._finished) return e2 = this._config.chunkSize, i2 = e2 ? (t = i2.substring(0, e2), i2.substring(e2)) : (t = i2, ""), this._finished = !i2, this.parseChunk(t);
        };
      }
      function p(e) {
        u.call(this, e = e || {});
        var t = [], i2 = true, r2 = false;
        this.pause = function() {
          u.prototype.pause.apply(this, arguments), this._input.pause();
        }, this.resume = function() {
          u.prototype.resume.apply(this, arguments), this._input.resume();
        }, this.stream = function(e2) {
          this._input = e2, this._input.on("data", this._streamData), this._input.on("end", this._streamEnd), this._input.on("error", this._streamError);
        }, this._checkIsFinished = function() {
          r2 && 1 === t.length && (this._finished = true);
        }, this._nextChunk = function() {
          this._checkIsFinished(), t.length ? this.parseChunk(t.shift()) : i2 = true;
        }, this._streamData = y(function(e2) {
          try {
            t.push("string" == typeof e2 ? e2 : e2.toString(this._config.encoding)), i2 && (i2 = false, this._checkIsFinished(), this.parseChunk(t.shift()));
          } catch (e3) {
            this._streamError(e3);
          }
        }, this), this._streamError = y(function(e2) {
          this._streamCleanUp(), this._sendError(e2);
        }, this), this._streamEnd = y(function() {
          this._streamCleanUp(), r2 = true, this._streamData("");
        }, this), this._streamCleanUp = y(function() {
          this._input.removeListener("data", this._streamData), this._input.removeListener("end", this._streamEnd), this._input.removeListener("error", this._streamError);
        }, this);
      }
      function i(m2) {
        var n2, s2, a2, t, o2 = Math.pow(2, 53), h2 = -o2, u2 = /^\s*-?(\d+\.?|\.\d+|\d+\.\d+)([eE][-+]?\d+)?\s*$/, d2 = /^((\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z)))$/, i2 = this, r2 = 0, f2 = 0, l2 = false, e = false, c2 = [], p2 = { data: [], errors: [], meta: {} };
        function y2(e2) {
          return "greedy" === m2.skipEmptyLines ? "" === e2.join("").trim() : 1 === e2.length && 0 === e2[0].length;
        }
        function g2() {
          if (p2 && a2 && (k("Delimiter", "UndetectableDelimiter", "Unable to auto-detect delimiting character; defaulted to '" + v.DefaultDelimiter + "'"), a2 = false), m2.skipEmptyLines && (p2.data = p2.data.filter(function(e3) {
            return !y2(e3);
          })), _2()) {
            let t3 = function(e3, t4) {
              e3 = P(e3), q(m2.transformHeader) && (e3 = m2.transformHeader(e3, t4)), c2.push(e3);
            };
            var t2 = t3;
            if (p2) if (Array.isArray(p2.data[0])) {
              for (var e2 = 0; _2() && e2 < p2.data.length; e2++) p2.data[e2].forEach(t3);
              p2.data.splice(0, 1);
            } else p2.data.forEach(t3);
          }
          function i3(e3, t3) {
            for (var i4 = m2.header ? {} : [], r4 = 0; r4 < e3.length; r4++) {
              var n3 = r4, s3 = e3[r4], s3 = ((e4, t4) => ((e5) => (m2.dynamicTypingFunction && void 0 === m2.dynamicTyping[e5] && (m2.dynamicTyping[e5] = m2.dynamicTypingFunction(e5)), true === (m2.dynamicTyping[e5] || m2.dynamicTyping)))(e4) ? "true" === t4 || "TRUE" === t4 || "false" !== t4 && "FALSE" !== t4 && (((e5) => {
                if (u2.test(e5)) {
                  e5 = parseFloat(e5);
                  if (h2 < e5 && e5 < o2) return 1;
                }
              })(t4) ? parseFloat(t4) : d2.test(t4) ? new Date(t4) : "" === t4 ? null : t4) : t4)(n3 = m2.header ? r4 >= c2.length ? "__parsed_extra" : c2[r4] : n3, s3 = m2.transform ? m2.transform(s3, n3) : s3);
              "__parsed_extra" === n3 ? (i4[n3] = i4[n3] || [], i4[n3].push(s3)) : i4[n3] = s3;
            }
            return m2.header && (r4 > c2.length ? k("FieldMismatch", "TooManyFields", "Too many fields: expected " + c2.length + " fields but parsed " + r4, f2 + t3) : r4 < c2.length && k("FieldMismatch", "TooFewFields", "Too few fields: expected " + c2.length + " fields but parsed " + r4, f2 + t3)), i4;
          }
          var r3;
          p2 && (m2.header || m2.dynamicTyping || m2.transform) && (r3 = 1, !p2.data.length || Array.isArray(p2.data[0]) ? (p2.data = p2.data.map(i3), r3 = p2.data.length) : p2.data = i3(p2.data, 0), m2.header && p2.meta && (p2.meta.fields = c2), f2 += r3);
        }
        function _2() {
          return m2.header && 0 === c2.length;
        }
        function k(e2, t2, i3, r3) {
          e2 = { type: e2, code: t2, message: i3 };
          void 0 !== r3 && (e2.row = r3), p2.errors.push(e2);
        }
        q(m2.step) && (t = m2.step, m2.step = function(e2) {
          p2 = e2, _2() ? g2() : (g2(), 0 !== p2.data.length && (r2 += e2.data.length, m2.preview && r2 > m2.preview ? s2.abort() : (p2.data = p2.data[0], t(p2, i2))));
        }), this.parse = function(e2, t2, i3) {
          var r3 = m2.quoteChar || '"', r3 = (m2.newline || (m2.newline = this.guessLineEndings(e2, r3)), a2 = false, m2.delimiter ? q(m2.delimiter) && (m2.delimiter = m2.delimiter(e2), p2.meta.delimiter = m2.delimiter) : ((r3 = ((e3, t3, i4, r4, n3) => {
            var s3, a3, o3, h3;
            n3 = n3 || [",", "	", "|", ";", v.RECORD_SEP, v.UNIT_SEP];
            for (var u3 = 0; u3 < n3.length; u3++) {
              for (var d3, f3 = n3[u3], l3 = 0, c3 = 0, p3 = 0, g3 = (o3 = void 0, new E({ comments: r4, delimiter: f3, newline: t3, preview: 10 }).parse(e3)), _3 = 0; _3 < g3.data.length; _3++) i4 && y2(g3.data[_3]) ? p3++ : (d3 = g3.data[_3].length, c3 += d3, void 0 === o3 ? o3 = d3 : 0 < d3 && (l3 += Math.abs(d3 - o3), o3 = d3));
              0 < g3.data.length && (c3 /= g3.data.length - p3), (void 0 === a3 || l3 <= a3) && (void 0 === h3 || h3 < c3) && 1.99 < c3 && (a3 = l3, s3 = f3, h3 = c3);
            }
            return { successful: !!(m2.delimiter = s3), bestDelimiter: s3 };
          })(e2, m2.newline, m2.skipEmptyLines, m2.comments, m2.delimitersToGuess)).successful ? m2.delimiter = r3.bestDelimiter : (a2 = true, m2.delimiter = v.DefaultDelimiter), p2.meta.delimiter = m2.delimiter), b(m2));
          return m2.preview && m2.header && r3.preview++, n2 = e2, s2 = new E(r3), p2 = s2.parse(n2, t2, i3), g2(), l2 ? { meta: { paused: true } } : p2 || { meta: { paused: false } };
        }, this.paused = function() {
          return l2;
        }, this.pause = function() {
          l2 = true, s2.abort(), n2 = q(m2.chunk) ? "" : n2.substring(s2.getCharIndex());
        }, this.resume = function() {
          i2.streamer._halted ? (l2 = false, i2.streamer.parseChunk(n2, true)) : setTimeout(i2.resume, 3);
        }, this.aborted = function() {
          return e;
        }, this.abort = function() {
          e = true, s2.abort(), p2.meta.aborted = true, q(m2.complete) && m2.complete(p2), n2 = "";
        }, this.guessLineEndings = function(e2, t2) {
          e2 = e2.substring(0, 1048576);
          var t2 = new RegExp(U(t2) + "([^]*?)" + U(t2), "gm"), i3 = (e2 = e2.replace(t2, "")).split("\r"), t2 = e2.split("\n"), e2 = 1 < t2.length && t2[0].length < i3[0].length;
          if (1 === i3.length || e2) return "\n";
          for (var r3 = 0, n3 = 0; n3 < i3.length; n3++) "\n" === i3[n3][0] && r3++;
          return r3 >= i3.length / 2 ? "\r\n" : "\r";
        };
      }
      function U(e) {
        return e.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      }
      function E(C) {
        var S = (C = C || {}).delimiter, O = C.newline, x = C.comments, I = C.step, A = C.preview, T = C.fastMode, D = null, L = false, F = null == C.quoteChar ? '"' : C.quoteChar, j = F;
        if (void 0 !== C.escapeChar && (j = C.escapeChar), ("string" != typeof S || -1 < v.BAD_DELIMITERS.indexOf(S)) && (S = ","), x === S) throw new Error("Comment character same as delimiter");
        true === x ? x = "#" : ("string" != typeof x || -1 < v.BAD_DELIMITERS.indexOf(x)) && (x = false), "\n" !== O && "\r" !== O && "\r\n" !== O && (O = "\n");
        var z = 0, M = false;
        this.parse = function(i2, t, r2) {
          if ("string" != typeof i2) throw new Error("Input must be a string");
          var n2 = i2.length, e = S.length, s2 = O.length, a2 = x.length, o2 = q(I), h2 = [], u2 = [], d2 = [], f2 = z = 0;
          if (!i2) return w();
          if (T || false !== T && -1 === i2.indexOf(F)) {
            for (var l2 = i2.split(O), c2 = 0; c2 < l2.length; c2++) {
              if (d2 = l2[c2], z += d2.length, c2 !== l2.length - 1) z += O.length;
              else if (r2) return w();
              if (!x || d2.substring(0, a2) !== x) {
                if (o2) {
                  if (h2 = [], k(d2.split(S)), R(), M) return w();
                } else k(d2.split(S));
                if (A && A <= c2) return h2 = h2.slice(0, A), w(true);
              }
            }
            return w();
          }
          for (var p2 = i2.indexOf(S, z), g2 = i2.indexOf(O, z), _2 = new RegExp(U(j) + U(F), "g"), m2 = i2.indexOf(F, z); ; ) if (i2[z] === F) for (m2 = z, z++; ; ) {
            if (-1 === (m2 = i2.indexOf(F, m2 + 1))) return r2 || u2.push({ type: "Quotes", code: "MissingQuotes", message: "Quoted field unterminated", row: h2.length, index: z }), E2();
            if (m2 === n2 - 1) return E2(i2.substring(z, m2).replace(_2, F));
            if (F === j && i2[m2 + 1] === j) m2++;
            else if (F === j || 0 === m2 || i2[m2 - 1] !== j) {
              -1 !== p2 && p2 < m2 + 1 && (p2 = i2.indexOf(S, m2 + 1));
              var y2 = v2(-1 === (g2 = -1 !== g2 && g2 < m2 + 1 ? i2.indexOf(O, m2 + 1) : g2) ? p2 : Math.min(p2, g2));
              if (i2.substr(m2 + 1 + y2, e) === S) {
                d2.push(i2.substring(z, m2).replace(_2, F)), i2[z = m2 + 1 + y2 + e] !== F && (m2 = i2.indexOf(F, z)), p2 = i2.indexOf(S, z), g2 = i2.indexOf(O, z);
                break;
              }
              y2 = v2(g2);
              if (i2.substring(m2 + 1 + y2, m2 + 1 + y2 + s2) === O) {
                if (d2.push(i2.substring(z, m2).replace(_2, F)), b2(m2 + 1 + y2 + s2), p2 = i2.indexOf(S, z), m2 = i2.indexOf(F, z), o2 && (R(), M)) return w();
                if (A && h2.length >= A) return w(true);
                break;
              }
              u2.push({ type: "Quotes", code: "InvalidQuotes", message: "Trailing quote on quoted field is malformed", row: h2.length, index: z }), m2++;
            }
          }
          else if (x && 0 === d2.length && i2.substring(z, z + a2) === x) {
            if (-1 === g2) return w();
            z = g2 + s2, g2 = i2.indexOf(O, z), p2 = i2.indexOf(S, z);
          } else if (-1 !== p2 && (p2 < g2 || -1 === g2)) d2.push(i2.substring(z, p2)), z = p2 + e, p2 = i2.indexOf(S, z);
          else {
            if (-1 === g2) break;
            if (d2.push(i2.substring(z, g2)), b2(g2 + s2), o2 && (R(), M)) return w();
            if (A && h2.length >= A) return w(true);
          }
          return E2();
          function k(e2) {
            h2.push(e2), f2 = z;
          }
          function v2(e2) {
            var t2 = 0;
            return t2 = -1 !== e2 && (e2 = i2.substring(m2 + 1, e2)) && "" === e2.trim() ? e2.length : t2;
          }
          function E2(e2) {
            return r2 || (void 0 === e2 && (e2 = i2.substring(z)), d2.push(e2), z = n2, k(d2), o2 && R()), w();
          }
          function b2(e2) {
            z = e2, k(d2), d2 = [], g2 = i2.indexOf(O, z);
          }
          function w(e2) {
            if (C.header && !t && h2.length && !L) {
              var s3 = h2[0], a3 = /* @__PURE__ */ Object.create(null), o3 = new Set(s3);
              let n3 = false;
              for (let r3 = 0; r3 < s3.length; r3++) {
                let i3 = P(s3[r3]);
                if (a3[i3 = q(C.transformHeader) ? C.transformHeader(i3, r3) : i3]) {
                  let e3, t2 = a3[i3];
                  for (; e3 = i3 + "_" + t2, t2++, o3.has(e3); ) ;
                  o3.add(e3), s3[r3] = e3, a3[i3]++, n3 = true, (D = null === D ? {} : D)[e3] = i3;
                } else a3[i3] = 1, s3[r3] = i3;
                o3.add(i3);
              }
              n3 && console.warn("Duplicate headers found and renamed."), L = true;
            }
            return { data: h2, errors: u2, meta: { delimiter: S, linebreak: O, aborted: M, truncated: !!e2, cursor: f2 + (t || 0), renamedHeaders: D } };
          }
          function R() {
            I(w()), h2 = [], u2 = [];
          }
        }, this.abort = function() {
          M = true;
        }, this.getCharIndex = function() {
          return z;
        };
      }
      function g(e) {
        var t = e.data, i2 = o[t.workerId], r2 = false;
        if (t.error) i2.userError(t.error, t.file);
        else if (t.results && t.results.data) {
          var n2 = { abort: function() {
            r2 = true, _(t.workerId, { data: [], errors: [], meta: { aborted: true } });
          }, pause: m, resume: m };
          if (q(i2.userStep)) {
            for (var s2 = 0; s2 < t.results.data.length && (i2.userStep({ data: t.results.data[s2], errors: t.results.errors, meta: t.results.meta }, n2), !r2); s2++) ;
            delete t.results;
          } else q(i2.userChunk) && (i2.userChunk(t.results, n2, t.file), delete t.results);
        }
        t.finished && !r2 && _(t.workerId, t.results);
      }
      function _(e, t) {
        var i2 = o[e];
        q(i2.userComplete) && i2.userComplete(t), i2.terminate(), delete o[e];
      }
      function m() {
        throw new Error("Not implemented.");
      }
      function b(e) {
        if ("object" != typeof e || null === e) return e;
        var t, i2 = Array.isArray(e) ? [] : {};
        for (t in e) i2[t] = b(e[t]);
        return i2;
      }
      function y(e, t) {
        return function() {
          e.apply(t, arguments);
        };
      }
      function q(e) {
        return "function" == typeof e;
      }
      return v.parse = function(e, t) {
        var i2 = (t = t || {}).dynamicTyping || false;
        q(i2) && (t.dynamicTypingFunction = i2, i2 = {});
        if (t.dynamicTyping = i2, t.transform = !!q(t.transform) && t.transform, !t.worker || !v.WORKERS_SUPPORTED) return i2 = null, v.NODE_STREAM_INPUT, "string" == typeof e ? (e = P(e), i2 = new (t.download ? f : c)(t)) : true === e.readable && q(e.read) && q(e.on) ? i2 = new p(t) : (n.File && e instanceof File || e instanceof Object) && (i2 = new l(t)), i2.stream(e);
        (i2 = (() => {
          var e2;
          return !!v.WORKERS_SUPPORTED && (e2 = (() => {
            var e3 = n.URL || n.webkitURL || null, t2 = r.toString();
            return v.BLOB_URL || (v.BLOB_URL = e3.createObjectURL(new Blob(["var global = (function() { if (typeof self !== 'undefined') { return self; } if (typeof window !== 'undefined') { return window; } if (typeof global !== 'undefined') { return global; } return {}; })(); global.IS_PAPA_WORKER=true; ", "(", t2, ")();"], { type: "text/javascript" })));
          })(), (e2 = new n.Worker(e2)).onmessage = g, e2.id = h++, o[e2.id] = e2);
        })()).userStep = t.step, i2.userChunk = t.chunk, i2.userComplete = t.complete, i2.userError = t.error, t.step = q(t.step), t.chunk = q(t.chunk), t.complete = q(t.complete), t.error = q(t.error), delete t.worker, i2.postMessage({ input: e, config: t, workerId: i2.id });
      }, v.unparse = function(e, t) {
        var s2 = false, _2 = true, m2 = ",", y2 = "\r\n", a2 = '"', o2 = a2 + a2, i2 = false, r2 = null, h2 = false, u2 = ((() => {
          if ("object" == typeof t) {
            if ("string" != typeof t.delimiter || v.BAD_DELIMITERS.filter(function(e2) {
              return -1 !== t.delimiter.indexOf(e2);
            }).length || (m2 = t.delimiter), "boolean" != typeof t.quotes && "function" != typeof t.quotes && !Array.isArray(t.quotes) || (s2 = t.quotes), "boolean" != typeof t.skipEmptyLines && "string" != typeof t.skipEmptyLines || (i2 = t.skipEmptyLines), "string" == typeof t.newline && (y2 = t.newline), "string" == typeof t.quoteChar && (a2 = t.quoteChar, o2 = a2 + a2), "boolean" == typeof t.header && (_2 = t.header), Array.isArray(t.columns)) {
              if (0 === t.columns.length) throw new Error("Option columns is empty");
              r2 = t.columns;
            }
            void 0 !== t.escapeChar && (o2 = t.escapeChar + a2), t.escapeFormulae instanceof RegExp ? h2 = t.escapeFormulae : "boolean" == typeof t.escapeFormulae && t.escapeFormulae && (h2 = /^[=+\-@\t\r].*$/);
          }
        })(), new RegExp(U(a2), "g"));
        "string" == typeof e && (e = JSON.parse(e));
        if (Array.isArray(e)) {
          if (!e.length || Array.isArray(e[0])) return n2(null, e, i2);
          if ("object" == typeof e[0]) return n2(r2 || Object.keys(e[0]), e, i2);
        } else if ("object" == typeof e) return "string" == typeof e.data && (e.data = JSON.parse(e.data)), Array.isArray(e.data) && (e.fields || (e.fields = e.meta && e.meta.fields || r2), e.fields || (e.fields = Array.isArray(e.data[0]) ? e.fields : "object" == typeof e.data[0] ? Object.keys(e.data[0]) : []), Array.isArray(e.data[0]) || "object" == typeof e.data[0] || (e.data = [e.data])), n2(e.fields || [], e.data || [], i2);
        throw new Error("Unable to serialize unrecognized input");
        function n2(e2, t2, i3) {
          var r3 = "", n3 = ("string" == typeof e2 && (e2 = JSON.parse(e2)), "string" == typeof t2 && (t2 = JSON.parse(t2)), Array.isArray(e2) && 0 < e2.length), s3 = !Array.isArray(t2[0]);
          if (n3 && _2) {
            for (var a3 = 0; a3 < e2.length; a3++) 0 < a3 && (r3 += m2), r3 += k(e2[a3], a3);
            0 < t2.length && (r3 += y2);
          }
          for (var o3 = 0; o3 < t2.length; o3++) {
            var h3 = (n3 ? e2 : t2[o3]).length, u3 = false, d2 = n3 ? 0 === Object.keys(t2[o3]).length : 0 === t2[o3].length;
            if (i3 && !n3 && (u3 = "greedy" === i3 ? "" === t2[o3].join("").trim() : 1 === t2[o3].length && 0 === t2[o3][0].length), "greedy" === i3 && n3) {
              for (var f2 = [], l2 = 0; l2 < h3; l2++) {
                var c2 = s3 ? e2[l2] : l2;
                f2.push(t2[o3][c2]);
              }
              u3 = "" === f2.join("").trim();
            }
            if (!u3) {
              for (var p2 = 0; p2 < h3; p2++) {
                0 < p2 && !d2 && (r3 += m2);
                var g2 = n3 && s3 ? e2[p2] : p2;
                r3 += k(t2[o3][g2], p2);
              }
              o3 < t2.length - 1 && (!i3 || 0 < h3 && !d2) && (r3 += y2);
            }
          }
          return r3;
        }
        function k(e2, t2) {
          var i3, r3, n3;
          return null == e2 ? "" : e2.constructor === Date ? JSON.stringify(e2).slice(1, 25) : (n3 = false, h2 && "string" == typeof e2 && h2.test(e2) && (e2 = "'" + e2, n3 = true), r3 = (i3 = e2.toString()).replace(u2, o2), (n3 = n3 || true === s2 || "function" == typeof s2 && s2(e2, t2) || Array.isArray(s2) && s2[t2] || ((e3, t3) => {
            for (var i4 = 0; i4 < t3.length; i4++) if (-1 < e3.indexOf(t3[i4])) return true;
            return false;
          })(r3, v.BAD_DELIMITERS) || -1 < r3.indexOf(m2) || -1 < i3.indexOf(a2) || " " === r3.charAt(0) || " " === r3.charAt(r3.length - 1)) ? a2 + r3 + a2 : r3);
        }
      }, v.RECORD_SEP = String.fromCharCode(30), v.UNIT_SEP = String.fromCharCode(31), v.BYTE_ORDER_MARK = "\uFEFF", v.BAD_DELIMITERS = ["\r", "\n", '"', v.BYTE_ORDER_MARK], v.WORKERS_SUPPORTED = !s && !!n.Worker, v.NODE_STREAM_INPUT = 1, v.LocalChunkSize = 10485760, v.RemoteChunkSize = 5242880, v.DefaultDelimiter = ",", v.Parser = E, v.ParserHandle = i, v.NetworkStreamer = f, v.FileStreamer = l, v.StringStreamer = c, v.ReadableStreamStreamer = p, n.jQuery && ((d = n.jQuery).fn.parse = function(o2) {
        var i2 = o2.config || {}, h2 = [];
        return this.each(function(e2) {
          if (!("INPUT" === d(this).prop("tagName").toUpperCase() && "file" === d(this).attr("type").toLowerCase() && n.FileReader) || !this.files || 0 === this.files.length) return true;
          for (var t = 0; t < this.files.length; t++) h2.push({ file: this.files[t], inputElem: this, instanceConfig: d.extend({}, i2) });
        }), e(), this;
        function e() {
          if (0 === h2.length) q(o2.complete) && o2.complete();
          else {
            var e2, t, i3, r2, n2 = h2[0];
            if (q(o2.before)) {
              var s2 = o2.before(n2.file, n2.inputElem);
              if ("object" == typeof s2) {
                if ("abort" === s2.action) return e2 = "AbortError", t = n2.file, i3 = n2.inputElem, r2 = s2.reason, void (q(o2.error) && o2.error({ name: e2 }, t, i3, r2));
                if ("skip" === s2.action) return void u2();
                "object" == typeof s2.config && (n2.instanceConfig = d.extend(n2.instanceConfig, s2.config));
              } else if ("skip" === s2) return void u2();
            }
            var a2 = n2.instanceConfig.complete;
            n2.instanceConfig.complete = function(e3) {
              q(a2) && a2(e3, n2.file, n2.inputElem), u2();
            }, v.parse(n2.file, n2.instanceConfig);
          }
        }
        function u2() {
          h2.splice(0, 1), e();
        }
      }), a && (n.onmessage = function(e) {
        e = e.data;
        void 0 === v.WORKER_ID && e && (v.WORKER_ID = e.workerId);
        "string" == typeof e.input ? n.postMessage({ workerId: v.WORKER_ID, results: v.parse(e.input, e.config), finished: true }) : (n.File && e.input instanceof File || e.input instanceof Object) && (e = v.parse(e.input, e.config)) && n.postMessage({ workerId: v.WORKER_ID, results: e, finished: true });
      }), (f.prototype = Object.create(u.prototype)).constructor = f, (l.prototype = Object.create(u.prototype)).constructor = l, (c.prototype = Object.create(c.prototype)).constructor = c, (p.prototype = Object.create(u.prototype)).constructor = p, v;
    });
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CSVQuizPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var VIEW_TYPE_QUIZ = "csv-quiz-practice-view";
var DEFAULT_SETTINGS = {
  csvPath: "\u9898\u5E93.csv",
  randomOrder: false,
  randomOptions: false,
  autoNextDelay: 1,
  filterPanelOpen: true,
  editPanelOpen: true,
  defaultFilterFavorite: "",
  defaultFilterMastered: "",
  defaultFilterRepeat: "",
  defaultFilterWrong: ""
};

// src/settings.ts
var import_obsidian = require("obsidian");
var CSVQuizSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /**
   * Obsidian 1.13.0+: 声明式设置。Obsidian 调用此方法并跳过 display()。
   * 控件自动绑定到 this.plugin.settings[key]。
   */
  getSettingDefinitions() {
    return [
      { name: "\u5237\u9898\u554A - \u8BBE\u7F6E" },
      {
        name: "CSV \u6587\u4EF6\u8DEF\u5F84",
        desc: "\u9898\u5E93 CSV \u6587\u4EF6\u76F8\u5BF9\u4E8E\u5E93\u6839\u76EE\u5F55\u7684\u8DEF\u5F84",
        control: {
          type: "file",
          key: "csvPath",
          defaultValue: DEFAULT_SETTINGS.csvPath,
          filter: (file) => file.extension === "csv"
        }
      },
      {
        name: "\u968F\u673A\u9898\u76EE\u987A\u5E8F",
        desc: "\u5F00\u542F\u540E\u6BCF\u6B21\u52A0\u8F7D\u65F6\u968F\u673A\u6392\u5217\u9898\u76EE\u987A\u5E8F",
        control: { type: "toggle", key: "randomOrder" }
      },
      {
        name: "\u968F\u673A\u9009\u9879\u987A\u5E8F",
        desc: "\u5F00\u542F\u540E\u6BCF\u4E2A\u9898\u76EE\u7684\u9009\u9879\u987A\u5E8F\u968F\u673A\u6392\u5217",
        control: { type: "toggle", key: "randomOptions" }
      },
      {
        name: "\u7B54\u5BF9\u81EA\u52A8\u8DF3\u8F6C\u5EF6\u8FDF\uFF08\u79D2\uFF09",
        desc: "\u7B54\u5BF9\u540E\u81EA\u52A8\u8DF3\u8F6C\u5230\u4E0B\u4E00\u9898\u7684\u7B49\u5F85\u65F6\u95F4\uFF0C0 \u8868\u793A\u4E0D\u81EA\u52A8\u8DF3\u8F6C",
        control: {
          type: "number",
          key: "autoNextDelay",
          min: 0,
          max: 30,
          defaultValue: DEFAULT_SETTINGS.autoNextDelay
        }
      },
      {
        name: "\u9ED8\u8BA4\u5C55\u5F00\u7B5B\u9009\u680F",
        desc: "\u6253\u5F00\u5237\u9898\u9762\u677F\u65F6\u7B5B\u9009\u680F\u9ED8\u8BA4\u662F\u5426\u5C55\u5F00",
        control: { type: "toggle", key: "filterPanelOpen" }
      },
      {
        name: "\u9ED8\u8BA4\u5C55\u5F00\u7F16\u8F91\u680F",
        desc: "\u6253\u5F00\u5237\u9898\u9762\u677F\u65F6\u6807\u7B7E/\u5206\u7C7B\u7F16\u8F91\u680F\u9ED8\u8BA4\u662F\u5426\u5C55\u5F00",
        control: { type: "toggle", key: "editPanelOpen" }
      },
      {
        type: "group",
        heading: "\u6807\u8BB0\u7B5B\u9009\u9ED8\u8BA4\u503C",
        items: [
          {
            name: "\u9ED8\u8BA4\u7B5B\u9009: \u6536\u85CF",
            desc: "\u6253\u5F00\u5237\u9898\u9762\u677F\u65F6\u300C\u6536\u85CF\u300D\u7B5B\u9009\u7684\u9ED8\u8BA4\u72B6\u6001",
            control: {
              type: "dropdown",
              key: "defaultFilterFavorite",
              options: { "": "\u4E0D\u9650", "1": "\u4EC5\u6536\u85CF", "0": "\u4E0D\u6536\u85CF" }
            }
          },
          {
            name: "\u9ED8\u8BA4\u7B5B\u9009: \u638C\u63E1",
            desc: "\u6253\u5F00\u5237\u9898\u9762\u677F\u65F6\u300C\u638C\u63E1\u300D\u7B5B\u9009\u7684\u9ED8\u8BA4\u72B6\u6001",
            control: {
              type: "dropdown",
              key: "defaultFilterMastered",
              options: { "": "\u4E0D\u9650", "1": "\u4EC5\u638C\u63E1", "0": "\u4E0D\u638C\u63E1" }
            }
          },
          {
            name: "\u9ED8\u8BA4\u7B5B\u9009: \u91CD\u590D",
            desc: "\u6253\u5F00\u5237\u9898\u9762\u677F\u65F6\u300C\u91CD\u590D\u300D\u7B5B\u9009\u7684\u9ED8\u8BA4\u72B6\u6001",
            control: {
              type: "dropdown",
              key: "defaultFilterRepeat",
              options: { "": "\u4E0D\u9650", "1": "\u4EC5\u91CD\u590D", "0": "\u4E0D\u91CD\u590D" }
            }
          },
          {
            name: "\u9ED8\u8BA4\u7B5B\u9009: \u9519\u9898",
            desc: "\u6253\u5F00\u5237\u9898\u9762\u677F\u65F6\u300C\u9519\u9898\u300D\u7B5B\u9009\u7684\u9ED8\u8BA4\u72B6\u6001",
            control: {
              type: "dropdown",
              key: "defaultFilterWrong",
              options: { "": "\u4E0D\u9650", "1": "\u4EC5\u9519\u9898", "0": "\u4E0D\u9519\u9898" }
            }
          }
        ]
      },
      {
        type: "group",
        heading: "\u7BA1\u7406",
        items: [
          {
            name: "\u91CD\u7F6E\u5237\u9898\u8FDB\u5EA6",
            desc: "\u6E05\u9664\u6240\u6709\u7B54\u9898\u8BB0\u5F55\u3001\u7EDF\u8BA1\u548C\u7B5B\u9009\u72B6\u6001\uFF0C\u91CD\u65B0\u52A0\u8F7D\u9898\u5E93",
            action: () => this.plugin.refreshQuiz()
          }
        ]
      }
    ];
  }
  /**
   * 1.13.0+: 从 this.plugin.settings 读取控件值。
   */
  getControlValue(key) {
    return this.plugin.settings[key];
  }
  /**
   * 1.13.0+: 写入控件值并持久化。
   * 必须通过 saveSettings()（StateManager 写队列）保存，以合并方式保留
   * data.json 中的 quizState；默认实现会调用 saveData(this.plugin.settings)
   * 从而覆盖整个 data.json 并丢失 quizState。
   */
  async setControlValue(key, value) {
    this.plugin.settings[key] = value;
    await this.plugin.saveSettings();
  }
  /**
   * < 1.13.0: Obsidian 调用此方法，保持原有命令式实现不变。
   * 注意：新增或修改设置时，需同步更新 display() 与 getSettingDefinitions()。
   */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u5237\u9898\u554A - \u8BBE\u7F6E").setHeading();
    this.addCSVPathSetting(containerEl);
    this.addToggleSetting(
      containerEl,
      "\u968F\u673A\u9898\u76EE\u987A\u5E8F",
      "\u5F00\u542F\u540E\u6BCF\u6B21\u52A0\u8F7D\u65F6\u968F\u673A\u6392\u5217\u9898\u76EE\u987A\u5E8F",
      "randomOrder"
    );
    this.addToggleSetting(
      containerEl,
      "\u968F\u673A\u9009\u9879\u987A\u5E8F",
      "\u5F00\u542F\u540E\u6BCF\u4E2A\u9898\u76EE\u7684\u9009\u9879\u987A\u5E8F\u968F\u673A\u6392\u5217",
      "randomOptions"
    );
    this.addNumberSetting(
      containerEl,
      "\u7B54\u5BF9\u81EA\u52A8\u8DF3\u8F6C\u5EF6\u8FDF\uFF08\u79D2\uFF09",
      "\u7B54\u5BF9\u540E\u81EA\u52A8\u8DF3\u8F6C\u5230\u4E0B\u4E00\u9898\u7684\u7B49\u5F85\u65F6\u95F4\uFF0C0 \u8868\u793A\u4E0D\u81EA\u52A8\u8DF3\u8F6C",
      "autoNextDelay",
      0,
      30
    );
    this.addToggleSetting(
      containerEl,
      "\u9ED8\u8BA4\u5C55\u5F00\u7B5B\u9009\u680F",
      "\u6253\u5F00\u5237\u9898\u9762\u677F\u65F6\u7B5B\u9009\u680F\u9ED8\u8BA4\u662F\u5426\u5C55\u5F00",
      "filterPanelOpen"
    );
    this.addToggleSetting(
      containerEl,
      "\u9ED8\u8BA4\u5C55\u5F00\u7F16\u8F91\u680F",
      "\u6253\u5F00\u5237\u9898\u9762\u677F\u65F6\u6807\u7B7E/\u5206\u7C7B\u7F16\u8F91\u680F\u9ED8\u8BA4\u662F\u5426\u5C55\u5F00",
      "editPanelOpen"
    );
    new import_obsidian.Setting(containerEl).setName("\u6807\u8BB0\u7B5B\u9009\u9ED8\u8BA4\u503C").setHeading();
    this.addFilterDefaultSetting(
      containerEl,
      "\u6536\u85CF",
      "defaultFilterFavorite"
    );
    this.addFilterDefaultSetting(
      containerEl,
      "\u638C\u63E1",
      "defaultFilterMastered"
    );
    this.addFilterDefaultSetting(
      containerEl,
      "\u91CD\u590D",
      "defaultFilterRepeat"
    );
    this.addFilterDefaultSetting(
      containerEl,
      "\u9519\u9898",
      "defaultFilterWrong"
    );
    new import_obsidian.Setting(containerEl).setName("\u7BA1\u7406").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u91CD\u7F6E\u5237\u9898\u8FDB\u5EA6").setDesc("\u6E05\u9664\u6240\u6709\u7B54\u9898\u8BB0\u5F55\u3001\u7EDF\u8BA1\u548C\u7B5B\u9009\u72B6\u6001\uFF0C\u91CD\u65B0\u52A0\u8F7D\u9898\u5E93").addButton(
      (btn) => btn.setButtonText("\u91CD\u7F6E").onClick(() => {
        this.plugin.refreshQuiz();
      })
    );
  }
  addCSVPathSetting(containerEl) {
    new import_obsidian.Setting(containerEl).setName("CSV \u6587\u4EF6\u8DEF\u5F84").setDesc("\u9898\u5E93 CSV \u6587\u4EF6\u76F8\u5BF9\u4E8E\u5E93\u6839\u76EE\u5F55\u7684\u8DEF\u5F84").addText(
      (text) => text.setPlaceholder("\u9898\u5E93.csv").setValue(this.plugin.settings.csvPath).onChange((value) => {
        this.plugin.settings.csvPath = value;
        void this.plugin.saveSettings();
      })
    ).addButton((btn) => {
      btn.setButtonText("\u4ECE\u5E93\u4E2D\u9009\u62E9").onClick(() => this.pickCSVFile());
    });
  }
  pickCSVFile() {
    const csvFiles = this.app.vault.getFiles().filter((f) => f.extension === "csv").map((f) => f.path);
    if (csvFiles.length === 0) {
      new import_obsidian.Notice("\u5E93\u4E2D\u6CA1\u6709\u627E\u5230 CSV \u6587\u4EF6");
      return;
    }
    const modal = new FilePickerModal(
      this.app,
      csvFiles,
      (selectedPath) => {
        this.plugin.settings.csvPath = selectedPath;
        void this.plugin.saveSettings();
      }
    );
    modal.open();
  }
  addToggleSetting(containerEl, name, desc, key) {
    new import_obsidian.Setting(containerEl).setName(name).setDesc(desc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings[key]).onChange((value) => {
        this.plugin.settings[key] = value;
        void this.plugin.saveSettings();
      })
    );
  }
  addNumberSetting(containerEl, name, desc, key, min, max) {
    new import_obsidian.Setting(containerEl).setName(name).setDesc(desc).addText(
      (text) => text.setPlaceholder(String(DEFAULT_SETTINGS[key])).setValue(String(this.plugin.settings[key])).onChange((value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= min && num <= max) {
          this.plugin.settings[key] = num;
          void this.plugin.saveSettings();
        }
      })
    );
  }
  addFilterDefaultSetting(containerEl, label, key) {
    new import_obsidian.Setting(containerEl).setName(`\u9ED8\u8BA4\u7B5B\u9009: ${label}`).setDesc(`\u6253\u5F00\u5237\u9898\u9762\u677F\u65F6\u300C${label}\u300D\u7B5B\u9009\u7684\u9ED8\u8BA4\u72B6\u6001`).addDropdown(
      (dd) => dd.addOption("", "\u4E0D\u9650").addOption("1", `\u4EC5${label}`).addOption("0", `\u4E0D${label}`).setValue(this.plugin.settings[key]).onChange((value) => {
        this.plugin.settings[key] = value;
        void this.plugin.saveSettings();
      })
    );
  }
};
var FilePickerModal = class extends import_obsidian.SuggestModal {
  constructor(app, files, onSelect) {
    super(app);
    this.files = files;
    this.onSelect = onSelect;
  }
  getSuggestions(query) {
    return this.files.filter(
      (f) => f.toLowerCase().includes(query.toLowerCase())
    );
  }
  renderSuggestion(file, el) {
    el.createEl("div", { text: file });
  }
  onChooseSuggestion(file, evt) {
    this.onSelect(file);
  }
};

// src/quizView.ts
var import_obsidian3 = require("obsidian");

// src/csvHandler.ts
var import_papaparse = __toESM(require_papaparse_min());
function parseCSV(content) {
  const result = import_papaparse.default.parse(content, { header: false, skipEmptyLines: true });
  const rows = result.data;
  if (rows.length > 0 && rows[0].length > 0) {
    rows[0][0] = rows[0][0].replace(/^\uFEFF/, "");
  }
  const dataRows = rows.slice(1);
  return dataRows.map((row) => ({
    id: String(row[0] || "").trim(),
    stem: row[1] || "",
    optionA: row[2] || "",
    optionB: row[3] || "",
    optionC: row[4] || "",
    optionD: row[5] || "",
    answer: (row[6] || "").toUpperCase().trim(),
    tags: row[7] || "",
    category1: row[8] || "",
    category2: row[9] || "",
    category3: row[10] || "",
    favorite: row[11] || "",
    mastered: row[12] || "",
    repeat: row[13] || "",
    wrong: row[14] || ""
  }));
}
function generateCSVRow(question) {
  return [
    question.id,
    question.stem,
    question.optionA,
    question.optionB,
    question.optionC,
    question.optionD,
    question.answer,
    question.tags,
    question.category1,
    question.category2,
    question.category3,
    question.favorite,
    question.mastered,
    question.repeat,
    question.wrong
  ];
}
function findAndUpdateRow(csvContent, questionId, newData) {
  const result = import_papaparse.default.parse(csvContent, { header: false, skipEmptyLines: true });
  const rows = result.data;
  if (rows.length < 2) return null;
  const header = rows[0];
  const dataRows = rows.slice(1);
  if (header.length > 0) {
    header[0] = header[0].replace(/^\uFEFF/, "");
  }
  const idx = dataRows.findIndex(
    (row) => String(row[0] || "").trim() === questionId
  );
  if (idx < 0) return null;
  dataRows[idx] = newData;
  return import_papaparse.default.unparse([header, ...dataRows], { delimiter: "," });
}
function getUniqueTags(questions) {
  const set = /* @__PURE__ */ new Set();
  for (const q of questions) {
    for (const tag of q.tags.split(/\s+/)) {
      const t = tag.trim();
      if (t.startsWith("#")) set.add(t);
    }
  }
  return [...set].sort((a, b) => a.localeCompare(b));
}
function getUniqueCategories(questions) {
  const cat1Set = /* @__PURE__ */ new Set();
  const cat2Set = /* @__PURE__ */ new Set();
  const cat3Set = /* @__PURE__ */ new Set();
  for (const q of questions) {
    if (q.category1) cat1Set.add(q.category1);
    if (q.category2) cat2Set.add(q.category2);
    if (q.category3) cat3Set.add(q.category3);
  }
  const sortFn = (a, b) => a.localeCompare(b);
  return {
    cat1: [...cat1Set].sort(sortFn),
    cat2: [...cat2Set].sort(sortFn),
    cat3: [...cat3Set].sort(sortFn)
  };
}
async function readCSVFile(vault, path) {
  return await vault.adapter.read(path);
}
async function writeCSVFile(vault, path, content) {
  await vault.adapter.write(path, "\uFEFF" + content);
}
function filterQuestions(questions, filterTags, filterCat1, filterCat2, filterCat3, filterFavorite = "", filterMastered = "", filterRepeat = "", filterWrong = "") {
  return questions.filter((q) => {
    if (filterTags && filterTags.trim() !== "") {
      const tagFilters = filterTags.trim().split(/\s+/).filter((t) => t.length > 0);
      for (const tag of tagFilters) {
        const tagStr = tag.startsWith("#") ? tag : "#" + tag;
        const escaped = tagStr.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        const re = new RegExp(`(?:^|\\s)${escaped}(?:$|\\s)`);
        if (!re.test(q.tags)) return false;
      }
    }
    if (filterCat1 && q.category1 !== filterCat1) return false;
    if (filterCat2 && q.category2 !== filterCat2) return false;
    if (filterCat3 && q.category3 !== filterCat3) return false;
    if (filterFavorite !== "" && q.favorite === "1" !== (filterFavorite === "1")) return false;
    if (filterMastered !== "" && q.mastered === "1" !== (filterMastered === "1")) return false;
    if (filterRepeat !== "" && q.repeat === "1" !== (filterRepeat === "1")) return false;
    if (filterWrong !== "" && q.wrong === "1" !== (filterWrong === "1")) return false;
    return true;
  });
}
function buildDisplayOrder(questions, randomOrder, savedOrder) {
  if (savedOrder && savedOrder.length === questions.length) {
    const savedSet = new Set(savedOrder);
    const allIds = new Set(questions.map((q) => q.id));
    if ([...savedSet].every((id) => allIds.has(id))) {
      return savedOrder;
    }
  }
  const ids = questions.map((q) => q.id);
  if (randomOrder) {
    return shuffleArray(ids);
  }
  return ids;
}
function shuffleArray(array) {
  const result = [...array];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}
var CSVWriteQueue = class {
  constructor(vault) {
    this.queue = [];
    this.processing = false;
    this.vault = vault;
  }
  enqueue(csvPath, transform) {
    return new Promise((resolve, reject) => {
      this.queue.push({ csvPath, transform, resolve, reject });
      void this.processNext();
    });
  }
  async processNext() {
    if (this.processing || this.queue.length === 0) return;
    this.processing = true;
    const item = this.queue.shift();
    try {
      const currentContent = await readCSVFile(this.vault, item.csvPath);
      const newContent = await Promise.resolve(item.transform(currentContent));
      await writeCSVFile(this.vault, item.csvPath, newContent);
      item.resolve();
    } catch (e) {
      item.reject(e);
    } finally {
      this.processing = false;
      void this.processNext();
    }
  }
  get pending() {
    return this.queue.length;
  }
  async drain() {
    while (this.processing || this.queue.length > 0) {
      await new Promise((resolve) => window.setTimeout(resolve, 10));
    }
  }
};

// src/utils.ts
function shuffle(array) {
  const result = [...array];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}
function sortByDisplayOrder(items, displayOrder) {
  const orderMap = /* @__PURE__ */ new Map();
  displayOrder.forEach((id, index) => orderMap.set(id, index));
  return [...items].sort((a, b) => {
    var _a, _b;
    const aIdx = (_a = orderMap.get(a.id)) != null ? _a : Number.MAX_SAFE_INTEGER;
    const bIdx = (_b = orderMap.get(b.id)) != null ? _b : Number.MAX_SAFE_INTEGER;
    return aIdx - bIdx;
  });
}
function quizStateEquals(a, b) {
  if (a === b) return true;
  if (!a || !b) return false;
  if (a.csvPath !== b.csvPath) return false;
  if (a.currentIndex !== b.currentIndex) return false;
  if (a.correctCount !== b.correctCount) return false;
  if (a.wrongCount !== b.wrongCount) return false;
  if (a.filterTags !== b.filterTags) return false;
  if (a.filterCat1 !== b.filterCat1) return false;
  if (a.filterCat2 !== b.filterCat2) return false;
  if (a.filterCat3 !== b.filterCat3) return false;
  if (a.filterFavorite !== b.filterFavorite) return false;
  if (a.filterMastered !== b.filterMastered) return false;
  if (a.filterRepeat !== b.filterRepeat) return false;
  if (a.filterWrong !== b.filterWrong) return false;
  if (a.displayOrder.length !== b.displayOrder.length) return false;
  for (let i = 0; i < a.displayOrder.length; i++) {
    if (a.displayOrder[i] !== b.displayOrder[i]) return false;
  }
  const ak = Object.keys(a.answeredQuestions);
  const bk = Object.keys(b.answeredQuestions);
  if (ak.length !== bk.length) return false;
  for (const k of ak) {
    if (a.answeredQuestions[k] !== b.answeredQuestions[k]) return false;
  }
  return true;
}

// src/modals.ts
var import_obsidian2 = require("obsidian");
var ChoiceModal = class extends import_obsidian2.Modal {
  constructor(app, opts) {
    super(app);
    this.resolved = false;
    this.opts = opts;
    this.promise = new Promise((resolve) => {
      this.resolveFn = resolve;
    });
  }
  onOpen() {
    this.titleEl.setText(this.opts.title);
    this.contentEl.empty();
    if (this.opts.message) {
      this.contentEl.createEl("p", {
        text: this.opts.message,
        cls: "csv-quiz-modal-message"
      });
    }
    const list = this.contentEl.createDiv("csv-quiz-modal-options");
    for (const opt of this.opts.options) {
      const item = list.createDiv("csv-quiz-modal-option");
      const btn = item.createEl("button", {
        text: opt.label,
        cls: "csv-quiz-btn csv-quiz-modal-btn" + (opt.cta ? " csv-quiz-btn-primary" : "") + (opt.danger ? " csv-quiz-btn-danger" : "")
      });
      btn.addEventListener("click", () => this.choose(opt.value));
      if (opt.description) {
        item.createEl("div", {
          text: opt.description,
          cls: "csv-quiz-modal-option-desc"
        });
      }
    }
  }
  onClose() {
    if (!this.resolved) {
      this.resolved = true;
      this.resolveFn(null);
    }
  }
  choose(value) {
    if (this.resolved) return;
    this.resolved = true;
    this.close();
    this.resolveFn(value);
  }
};

// src/quizView.ts
var QuizView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin, stateManager, vault, csvWriteQueue) {
    super(leaf);
    this.allQuestions = [];
    this.orderedQuestions = [];
    this.filteredQuestions = [];
    this.displayOrder = [];
    this.currentIndex = 0;
    this.correctCount = 0;
    this.wrongCount = 0;
    this.filterTags = "";
    this.filterCat1 = "";
    this.filterCat2 = "";
    this.filterCat3 = "";
    this.filterFavorite = "";
    this.filterMastered = "";
    this.filterRepeat = "";
    this.filterWrong = "";
    this.csvPath = "";
    this.answeredQuestions = {};
    this.currentShuffledQId = null;
    this.currentShuffledOptions = [];
    this.answering = false;
    this.showingAnswer = false;
    this.selectedOption = null;
    this.autoNextTimer = null;
    this.autoSaveTimer = null;
    this.isClosed = false;
    this.plugin = plugin;
    this.stateManager = stateManager;
    this.vault = vault;
    this.csvWriteQueue = csvWriteQueue;
  }
  getViewType() {
    return VIEW_TYPE_QUIZ;
  }
  getDisplayText() {
    return "\u5237\u9898\u554A";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    this.contentEl.addClass("csv-quiz-container");
    this.contentEl.empty();
    this.buildLayout();
    await this.initializeFromState();
  }
  async onClose() {
    if (this.isClosed) return;
    this.isClosed = true;
    this.cancelAutoNext();
    if (this.autoSaveTimer !== null) {
      window.clearInterval(this.autoSaveTimer);
      this.autoSaveTimer = null;
    }
    this.stateManager.cancelScheduledSave();
    if (this.stateManager.getState()) {
      await this.stateManager.saveStateImmediately(this.buildCurrentState());
    }
    await this.csvWriteQueue.drain();
  }
  buildLayout() {
    this.contentEl.empty();
    const infoBar = this.contentEl.createDiv("csv-quiz-info-bar");
    this.progressEl = infoBar.createDiv("csv-quiz-progress");
    this.statsEl = infoBar.createDiv("csv-quiz-stats");
    this.questionArea = this.contentEl.createDiv("csv-quiz-question-area");
    this.feedbackArea = this.contentEl.createDiv("csv-quiz-feedback");
    this.checkboxArea = this.contentEl.createDiv("csv-quiz-checkbox-area");
    this.readOnlyArea = this.contentEl.createDiv("csv-quiz-readonly-area");
    this.navigationArea = this.contentEl.createDiv("csv-quiz-nav");
    this.bottomBar = this.contentEl.createDiv("csv-quiz-bottom-bar");
    this.filterContainer = this.contentEl.createDiv(
      "csv-quiz-filter-panel"
    );
    this.editArea = this.contentEl.createDiv("csv-quiz-edit-area");
    this.contentEl.createDiv("csv-quiz-bottom-spacer");
  }
  async initializeFromState() {
    const inMemoryState = this.stateManager.getState();
    const pluginData = await this.stateManager.loadPluginData(this.getSettings());
    const settings = pluginData.settings;
    const diskState = pluginData.quizState;
    this.csvPath = settings.csvPath;
    this.buildFilterPanel(settings);
    this.stateManager.setState(null);
    let effectiveSavedState = diskState;
    if (inMemoryState && !quizStateEquals(inMemoryState, diskState)) {
      const choice = await this.askExternalModificationChoice(diskState === null);
      if (choice === "current") {
        effectiveSavedState = inMemoryState;
      } else if (choice === "external") {
        effectiveSavedState = diskState;
      } else {
        this.showError("\u5DF2\u53D6\u6D88\u52A0\u8F7D\u9898\u5E93\u3002\u8BF7\u91CD\u65B0\u6253\u5F00\u5237\u9898\u9762\u677F\u3002");
        return;
      }
    }
    if (effectiveSavedState && effectiveSavedState.csvPath !== this.csvPath) {
      const reset = await this.askResetChoice();
      if (reset === null) {
        this.showError("\u5DF2\u53D6\u6D88\u52A0\u8F7D\u9898\u5E93\u3002\u8BF7\u91CD\u65B0\u6253\u5F00\u5237\u9898\u9762\u677F\u3002");
        return;
      }
      if (reset === "keep") {
        const again = await this.askResetOrAbort();
        if (again !== "reset") {
          this.showError(
            "\u9898\u5E93\u8DEF\u5F84\u5DF2\u53D8\u66F4\uFF0C\u672A\u91CD\u7F6E\u8FDB\u5EA6\u65E0\u6CD5\u6B63\u5E38\u6253\u5F00\u9898\u5E93\u3002\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u70B9\u51FB\u300C\u91CD\u7F6E\u5237\u9898\u8FDB\u5EA6\u300D\u540E\u91CD\u8BD5\u3002"
          );
          return;
        }
      }
      const status2 = await this.loadQuestions();
      if (status2 !== "ok") {
        if (status2 === "error") this.restoreFiltersOnly(effectiveSavedState);
        this.startAutoSave();
        return;
      }
      this.applyFreshStart(settings, effectiveSavedState);
      this.updateFilterUI();
      this.renderQuestion();
      this.saveState();
      this.startAutoSave();
      return;
    }
    const status = await this.loadQuestions();
    if (status !== "ok") {
      if (status === "error") this.restoreFiltersOnly(effectiveSavedState);
      this.startAutoSave();
      return;
    }
    if (effectiveSavedState && effectiveSavedState.csvPath === this.csvPath) {
      this.applyRestore(settings, effectiveSavedState);
    } else {
      this.applyFreshStart(settings, effectiveSavedState);
    }
    this.updateFilterUI();
    this.renderQuestion();
    this.saveState();
    this.startAutoSave();
  }
  /** Read and parse the CSV. Returns "ok", "empty" (no questions), or "error". */
  async loadQuestions() {
    try {
      const csvContent = await readCSVFile(this.vault, this.csvPath);
      this.allQuestions = parseCSV(csvContent);
      if (this.allQuestions.length === 0) {
        this.showError("CSV \u6587\u4EF6\u4E2D\u6CA1\u6709\u627E\u5230\u9898\u76EE\u6570\u636E");
        return "empty";
      }
      return "ok";
    } catch (e) {
      console.error("CSV Quiz: Failed to load CSV", e);
      this.showError(`\u65E0\u6CD5\u52A0\u8F7D CSV \u6587\u4EF6: ${e instanceof Error ? e.message : String(e)}`);
      return "error";
    }
  }
  /** Fresh start: keep filters from savedState if present (else defaults), reset progress. */
  applyFreshStart(settings, savedState) {
    if (savedState) {
      this.filterTags = savedState.filterTags || "";
      this.filterCat1 = savedState.filterCat1 || "";
      this.filterCat2 = savedState.filterCat2 || "";
      this.filterCat3 = savedState.filterCat3 || "";
      this.filterFavorite = savedState.filterFavorite || "";
      this.filterMastered = savedState.filterMastered || "";
      this.filterRepeat = savedState.filterRepeat || "";
      this.filterWrong = savedState.filterWrong || "";
    } else {
      const s = this.getSettings();
      this.filterFavorite = s.defaultFilterFavorite;
      this.filterMastered = s.defaultFilterMastered;
      this.filterRepeat = s.defaultFilterRepeat;
      this.filterWrong = s.defaultFilterWrong;
    }
    this.displayOrder = buildDisplayOrder(this.allQuestions, settings.randomOrder);
    this.orderedQuestions = sortByDisplayOrder(this.allQuestions, this.displayOrder);
    this.filteredQuestions = filterQuestions(
      this.orderedQuestions,
      this.filterTags,
      this.filterCat1,
      this.filterCat2,
      this.filterCat3,
      this.filterFavorite,
      this.filterMastered,
      this.filterRepeat,
      this.filterWrong
    );
    this.currentIndex = 0;
    this.correctCount = 0;
    this.wrongCount = 0;
    this.answeredQuestions = {};
    this.currentShuffledQId = null;
  }
  /** Restore a full session state whose csvPath matches the current CSV. */
  applyRestore(settings, savedState) {
    this.filterTags = savedState.filterTags || "";
    this.filterCat1 = savedState.filterCat1 || "";
    this.filterCat2 = savedState.filterCat2 || "";
    this.filterCat3 = savedState.filterCat3 || "";
    this.filterFavorite = savedState.filterFavorite || "";
    this.filterMastered = savedState.filterMastered || "";
    this.filterRepeat = savedState.filterRepeat || "";
    this.filterWrong = savedState.filterWrong || "";
    this.displayOrder = buildDisplayOrder(
      this.allQuestions,
      settings.randomOrder,
      savedState.displayOrder
    );
    this.orderedQuestions = sortByDisplayOrder(this.allQuestions, this.displayOrder);
    this.filteredQuestions = filterQuestions(
      this.orderedQuestions,
      this.filterTags,
      this.filterCat1,
      this.filterCat2,
      this.filterCat3,
      this.filterFavorite,
      this.filterMastered,
      this.filterRepeat,
      this.filterWrong
    );
    this.currentIndex = Math.min(
      savedState.currentIndex,
      this.filteredQuestions.length - 1
    );
    if (this.currentIndex < 0) this.currentIndex = 0;
    this.correctCount = savedState.correctCount;
    this.wrongCount = savedState.wrongCount;
    this.answeredQuestions = savedState.answeredQuestions || {};
  }
  /** On CSV load failure: keep filters from saved state so the UI is not blank. */
  restoreFiltersOnly(savedState) {
    if (!savedState) return;
    this.filterTags = savedState.filterTags || "";
    this.filterCat1 = savedState.filterCat1 || "";
    this.filterCat2 = savedState.filterCat2 || "";
    this.filterCat3 = savedState.filterCat3 || "";
    this.filterFavorite = savedState.filterFavorite || "";
    this.filterMastered = savedState.filterMastered || "";
    this.filterRepeat = savedState.filterRepeat || "";
    this.filterWrong = savedState.filterWrong || "";
    this.updateFilterUI();
  }
  /** Periodic auto-save every 5s to protect against sudden app close. */
  startAutoSave() {
    if (this.autoSaveTimer !== null) {
      window.clearInterval(this.autoSaveTimer);
    }
    this.autoSaveTimer = window.setInterval(() => {
      if (this.stateManager.getState()) {
        this.stateManager.scheduleSave(this.buildCurrentState(), 0);
      }
    }, 5e3);
  }
  /** Ask the user whether to keep the in-memory progress or the externally-modified one. */
  async askExternalModificationChoice(diskIsEmpty) {
    const modal = new ChoiceModal(this.app, {
      title: "\u68C0\u6D4B\u5230\u5237\u9898\u8FDB\u5EA6\u88AB\u5916\u90E8\u4FEE\u6539",
      message: "\u5237\u9898\u8FDB\u5EA6\u6570\u636E\uFF08data.json\uFF09\u5DF2\u88AB\u5916\u90E8\u7F16\u8F91\u6216\u540C\u6B65\uFF0C\u4E0E\u5F53\u524D\u8FDB\u5EA6\u4E0D\u4E00\u81F4\u3002\u8BF7\u9009\u62E9\u8981\u4F7F\u7528\u7684\u8FDB\u5EA6\u3002",
      options: [
        {
          label: "\u4F7F\u7528\u5F53\u524D\u8FDB\u5EA6",
          value: "current",
          description: "\u4F7F\u7528\u672C\u6B21\u4F1A\u8BDD\u4E2D\u5185\u5B58\u91CC\u4FDD\u7559\u7684\u8FDB\u5EA6",
          cta: true
        },
        {
          label: diskIsEmpty ? "\u4F7F\u7528\u5916\u90E8\u8FDB\u5EA6\uFF08\u5DF2\u6E05\u7A7A\uFF09" : "\u4F7F\u7528\u5916\u90E8\u4FEE\u6539\u7684\u8FDB\u5EA6",
          value: "external",
          description: "\u4F7F\u7528\u5916\u90E8\u4FEE\u6539\u540E\u7684\u8FDB\u5EA6\u6570\u636E"
        }
      ]
    });
    modal.open();
    const res = await modal.promise;
    if (res === "current") return "current";
    if (res === "external") return "external";
    return null;
  }
  /** Ask the user whether to reset progress after a csvPath change. */
  async askResetChoice() {
    const modal = new ChoiceModal(this.app, {
      title: "\u9898\u5E93\u8DEF\u5F84\u5DF2\u53D8\u66F4",
      message: "\u5DF2\u4FDD\u5B58\u7684\u5237\u9898\u8FDB\u5EA6\u5C5E\u4E8E\u53E6\u4E00\u4E2A\u9898\u5E93\uFF08\u8DEF\u5F84\u4E0D\u540C\uFF09\u3002\u4FDD\u7559\u65E7\u8FDB\u5EA6\u4F1A\u5BFC\u81F4\u7A0B\u5E8F\u8FD0\u884C\u5F02\u5E38\u3002\u662F\u5426\u91CD\u7F6E\u5237\u9898\u8FDB\u5EA6\uFF1F",
      options: [
        {
          label: "\u91CD\u7F6E\u8FDB\u5EA6",
          value: "reset",
          description: "\u6E05\u9664\u65E7\u8FDB\u5EA6\uFF0C\u91CD\u65B0\u5F00\u59CB\u5237\u9898",
          cta: true
        },
        {
          label: "\u4FDD\u7559\u8FDB\u5EA6",
          value: "keep",
          description: "\u5C1D\u8BD5\u4FDD\u7559\u65E7\u8FDB\u5EA6\uFF08\u53EF\u80FD\u5BFC\u81F4\u8FD0\u884C\u5F02\u5E38\uFF09"
        }
      ]
    });
    modal.open();
    const res = await modal.promise;
    if (res === "reset") return "reset";
    if (res === "keep") return "keep";
    return null;
  }
  /** Re-ask after the user insisted on keeping incompatible progress. */
  async askResetOrAbort() {
    const modal = new ChoiceModal(this.app, {
      title: "\u65E0\u6CD5\u4FDD\u7559\u65E7\u8FDB\u5EA6",
      message: "\u65E7\u8FDB\u5EA6\u5BF9\u5E94\u7684\u662F\u53E6\u4E00\u4E2A\u9898\u5E93\uFF0C\u4FDD\u7559\u4F1A\u5BFC\u81F4\u7A0B\u5E8F\u8FD0\u884C\u5F02\u5E38\u3002\u8BF7\u91CD\u7F6E\u8FDB\u5EA6\uFF0C\u6216\u53D6\u6D88\u6253\u5F00\u9898\u5E93\u3002",
      options: [
        {
          label: "\u91CD\u7F6E\u8FDB\u5EA6",
          value: "reset",
          description: "\u6E05\u9664\u65E7\u8FDB\u5EA6\uFF0C\u91CD\u65B0\u5F00\u59CB\u5237\u9898",
          cta: true
        },
        {
          label: "\u53D6\u6D88\u6253\u5F00",
          value: "abort",
          description: "\u4E0D\u52A0\u8F7D\u9898\u5E93\uFF0C\u4FDD\u6301\u5F53\u524D\u72B6\u6001",
          danger: true
        }
      ]
    });
    modal.open();
    const res = await modal.promise;
    if (res === "reset") return "reset";
    if (res === "abort") return "abort";
    return null;
  }
  buildFilterPanel(settings) {
    this.filterContainer.empty();
    const toggleHeader = this.filterContainer.createDiv(
      "csv-quiz-filter-toggle"
    );
    const toggleIcon = toggleHeader.createSpan("csv-quiz-filter-icon");
    toggleHeader.createEl("span", { text: "\u7B5B\u9009\u6761\u4EF6" });
    const panelOpen = settings.filterPanelOpen;
    const filterBody = this.filterContainer.createDiv(
      "csv-quiz-filter-body"
    );
    toggleHeader.addEventListener("click", () => {
      const isHidden = filterBody.classList.contains("csv-quiz-filter-body-hidden");
      filterBody.classList.toggle("csv-quiz-filter-body-hidden");
      toggleIcon.textContent = isHidden ? "\u25BC" : "\u25B6";
    });
    filterBody.classList.toggle("csv-quiz-filter-body-hidden", !panelOpen);
    toggleIcon.textContent = panelOpen ? "\u25BC" : "\u25B6";
    const tagRow = filterBody.createDiv("csv-quiz-filter-row");
    tagRow.createEl("label", { text: "\u6807\u7B7E: ", cls: "csv-quiz-filter-label" });
    this.tagsContainer = tagRow.createDiv("csv-quiz-tags-container");
    const catRow = filterBody.createDiv("csv-quiz-filter-row");
    catRow.createEl("label", { text: "\u5206\u7C7B: ", cls: "csv-quiz-filter-label" });
    const catSelectors = catRow.createDiv("csv-quiz-filter-selectors");
    this.cat1Select = catSelectors.createEl("select", {
      cls: "csv-quiz-select csv-quiz-filter-select"
    });
    this.cat2Select = catSelectors.createEl("select", {
      cls: "csv-quiz-select csv-quiz-filter-select"
    });
    this.cat3Select = catSelectors.createEl("select", {
      cls: "csv-quiz-select csv-quiz-filter-select"
    });
    this.cat1Select.addEventListener("change", () => {
      void this.saveCurrentEdit().then(() => {
        this.filterCat1 = this.cat1Select.value;
        this.applyFiltersAndReset();
      });
    });
    this.cat2Select.addEventListener("change", () => {
      void this.saveCurrentEdit().then(() => {
        this.filterCat2 = this.cat2Select.value;
        this.applyFiltersAndReset();
      });
    });
    this.cat3Select.addEventListener("change", () => {
      void this.saveCurrentEdit().then(() => {
        this.filterCat3 = this.cat3Select.value;
        this.applyFiltersAndReset();
      });
    });
    const boolRow = filterBody.createDiv("csv-quiz-filter-row");
    boolRow.createEl("label", { text: "\u6807\u8BB0: ", cls: "csv-quiz-filter-label" });
    const boolFilters = [
      { key: "filterFavorite", label: "\u6536\u85CF", value: this.filterFavorite },
      { key: "filterMastered", label: "\u638C\u63E1", value: this.filterMastered },
      { key: "filterRepeat", label: "\u91CD\u590D", value: this.filterRepeat },
      { key: "filterWrong", label: "\u9519\u9898", value: this.filterWrong }
    ];
    for (const bf of boolFilters) {
      const group = boolRow.createSpan({ cls: "csv-quiz-bool-group" });
      group.createSpan({ text: bf.label, cls: "csv-quiz-bool-label" });
      const posChip = group.createEl("span", {
        text: "\u662F",
        cls: "csv-quiz-bool-chip" + (bf.value === "1" ? " csv-quiz-bool-chip-active" : ""),
        attr: { "data-bool-key": bf.key, "data-bool-val": "1" }
      });
      posChip.addEventListener("click", () => {
        void this.toggleBoolFilter(bf.key, "1");
      });
      const negChip = group.createEl("span", {
        text: "\u5426",
        cls: "csv-quiz-bool-chip" + (bf.value === "0" ? " csv-quiz-bool-chip-active csv-quiz-bool-chip-inverse" : ""),
        attr: { "data-bool-key": bf.key, "data-bool-val": "0" }
      });
      negChip.addEventListener("click", () => {
        void this.toggleBoolFilter(bf.key, "0");
      });
    }
  }
  updateFilterUI() {
    if (!this.cat1Select) return;
    const cats = getUniqueCategories(this.allQuestions);
    this.populateSelect(this.cat1Select, cats.cat1, this.filterCat1);
    this.populateSelect(this.cat2Select, cats.cat2, this.filterCat2);
    this.populateSelect(this.cat3Select, cats.cat3, this.filterCat3);
    this.populateTagChips();
    this.syncBoolChips();
  }
  syncBoolChips() {
    var _a;
    const chips = (_a = this.filterContainer) == null ? void 0 : _a.querySelectorAll(".csv-quiz-bool-chip");
    if (!chips) return;
    const map = {
      filterFavorite: this.filterFavorite,
      filterMastered: this.filterMastered,
      filterRepeat: this.filterRepeat,
      filterWrong: this.filterWrong
    };
    Array.from(chips).forEach((chip) => {
      const key = chip.getAttribute("data-bool-key") || "";
      const val = chip.getAttribute("data-bool-val") || "";
      const active = map[key] === val;
      chip.classList.toggle("csv-quiz-bool-chip-active", active);
      chip.classList.toggle("csv-quiz-bool-chip-inverse", active && val === "0");
    });
  }
  async toggleBoolFilter(key, val) {
    await this.saveCurrentEdit();
    const self2 = this;
    self2[key] = self2[key] === val ? "" : val;
    this.syncBoolChips();
    this.applyFiltersAndReset();
  }
  populateTagChips() {
    if (!this.tagsContainer) return;
    this.tagsContainer.empty();
    const selectedSet = new Set(
      this.filterTags.trim().split(/\s+/).filter((t) => t.length > 0)
    );
    const allTags = getUniqueTags(this.allQuestions);
    if (allTags.length === 0) {
      this.tagsContainer.createEl("span", {
        text: "\u65E0\u6807\u7B7E",
        cls: "csv-quiz-tag-chip csv-quiz-tag-chip-empty"
      });
      return;
    }
    for (const tag of allTags) {
      const chip = this.tagsContainer.createEl("span", {
        text: tag,
        cls: "csv-quiz-tag-chip" + (selectedSet.has(tag) ? " csv-quiz-tag-chip-selected" : "")
      });
      chip.dataset.tag = tag;
      chip.addEventListener("click", () => {
        void (async () => {
          await this.saveCurrentEdit();
          const tagStr = chip.dataset.tag;
          const current = this.filterTags.trim().split(/\s+/).filter((t) => t.length > 0);
          const idx = current.indexOf(tagStr);
          if (idx >= 0) {
            current.splice(idx, 1);
          } else {
            current.push(tagStr);
          }
          this.filterTags = current.join(" ");
          this.populateTagChips();
          this.applyFiltersAndReset();
        })();
      });
    }
  }
  populateSelect(select, options, currentValue) {
    select.empty();
    const allOpt = select.createEl("option", { text: "\u5168\u90E8" });
    allOpt.value = "";
    for (const opt of options) {
      const el = select.createEl("option", { text: opt });
      el.value = opt;
    }
    if (currentValue && options.includes(currentValue)) {
      select.value = currentValue;
    } else {
      select.value = "";
    }
  }
  reFilterForNavigation() {
    var _a;
    const prevId = (_a = this.filteredQuestions[this.currentIndex]) == null ? void 0 : _a.id;
    this.filteredQuestions = filterQuestions(
      this.orderedQuestions,
      this.filterTags,
      this.filterCat1,
      this.filterCat2,
      this.filterCat3,
      this.filterFavorite,
      this.filterMastered,
      this.filterRepeat,
      this.filterWrong
    );
    if (prevId) {
      const newIdx = this.filteredQuestions.findIndex((q) => q.id === prevId);
      if (newIdx >= 0) {
        this.currentIndex = newIdx;
      } else if (this.currentIndex >= this.filteredQuestions.length) {
        this.currentIndex = Math.max(0, this.filteredQuestions.length - 1);
      }
    }
  }
  applyFiltersAndReset() {
    this.filteredQuestions = filterQuestions(
      this.orderedQuestions,
      this.filterTags,
      this.filterCat1,
      this.filterCat2,
      this.filterCat3,
      this.filterFavorite,
      this.filterMastered,
      this.filterRepeat,
      this.filterWrong
    );
    this.currentIndex = this.filteredQuestions.length > 0 ? 0 : -1;
    this.currentShuffledQId = null;
    this.cancelAutoNext();
    this.renderQuestion();
    this.saveState();
  }
  renderQuestion() {
    this.questionArea.empty();
    this.feedbackArea.empty();
    this.editArea.empty();
    this.updateProgress();
    if (this.filteredQuestions.length === 0 || this.currentIndex < 0 || this.currentIndex >= this.filteredQuestions.length) {
      this.questionArea.createEl("p", {
        text: "\u6CA1\u6709\u5339\u914D\u7684\u9898\u76EE",
        cls: "csv-quiz-empty"
      });
      this.updateNavigation();
      return;
    }
    const question = this.filteredQuestions[this.currentIndex];
    const prevAnswer = this.answeredQuestions[question.id];
    if (prevAnswer) {
      this.selectedOption = prevAnswer;
      this.showingAnswer = true;
      this.answering = true;
    } else {
      this.selectedOption = null;
      this.showingAnswer = false;
      this.answering = false;
    }
    const stemDiv = this.questionArea.createDiv("csv-quiz-stem");
    import_obsidian3.MarkdownRenderer.render(this.app, question.stem, stemDiv, "", this).catch(
      (e) => console.error("CSV Quiz: markdown render failed", e)
    );
    const optionsDiv = this.questionArea.createDiv("csv-quiz-options");
    const optionKeys = [
      { key: "A", text: question.optionA },
      { key: "B", text: question.optionB },
      { key: "C", text: question.optionC },
      { key: "D", text: question.optionD }
    ];
    const settings = this.getSettings();
    let displayOptions = optionKeys;
    if (settings.randomOptions) {
      if (this.currentShuffledQId === question.id) {
        displayOptions = this.currentShuffledOptions;
      } else {
        displayOptions = shuffle(optionKeys);
        this.currentShuffledQId = question.id;
        this.currentShuffledOptions = displayOptions;
      }
    }
    const correctDisplayIdx = displayOptions.findIndex(
      (o) => o.key === question.answer
    );
    const correctDisplayLetter = correctDisplayIdx >= 0 ? String.fromCharCode(65 + correctDisplayIdx) : question.answer;
    for (let i = 0; i < displayOptions.length; i++) {
      const opt = displayOptions[i];
      const displayLetter = String.fromCharCode(65 + i);
      const optDiv = optionsDiv.createDiv(
        "csv-quiz-option" + (this.selectedOption === opt.key ? " csv-quiz-option-selected" : "") + (this.showingAnswer && opt.key === question.answer ? " csv-quiz-option-correct" : "") + (this.showingAnswer && this.selectedOption === opt.key && opt.key !== question.answer ? " csv-quiz-option-wrong" : "")
      );
      const radio = optDiv.createEl("input", {
        type: "radio",
        attr: { name: "quiz-option", id: `opt-${opt.key}` }
      });
      radio.value = opt.key;
      radio.checked = this.selectedOption === opt.key;
      const label = optDiv.createEl("label", {
        attr: { for: `opt-${opt.key}` }
      });
      label.createSpan({
        text: `${displayLetter}. ${opt.text}`
      });
      if (!this.answering && !this.showingAnswer) {
        optDiv.addEventListener("click", () => {
          void this.handleAnswer(opt.key);
        });
      }
    }
    this.renderFeedback(question, correctDisplayLetter);
    this.renderCheckboxArea(question);
    this.readOnlyArea.empty();
    const tagsChips = this.readOnlyArea.createSpan({ cls: "csv-quiz-readonly-tags" });
    tagsChips.createEl("strong", { text: "\u6807\u7B7E:  " });
    const tagText = question.tags || "\uFF08\u65E0\uFF09";
    for (const tag of tagText.split(/\s+/).filter(Boolean)) {
      tagsChips.createEl("span", { text: tag, cls: "csv-quiz-tag-chip csv-quiz-tag-chip-selected" });
    }
    const catText = `  |  \u4E00\u7EA7: ${question.category1 || "\uFF08\u65E0\uFF09"}  |  \u4E8C\u7EA7: ${question.category2 || "\uFF08\u65E0\uFF09"}  |  \u4E09\u7EA7: ${question.category3 || "\uFF08\u65E0\uFF09"}`;
    this.readOnlyArea.createSpan({ text: catText, cls: "csv-quiz-readonly-cats" });
    this.renderEditArea(question);
    this.updateNavigation();
  }
  renderFeedback(question, correctDisplayLetter) {
    this.feedbackArea.empty();
    if (!this.showingAnswer) return;
    const isCorrect = this.selectedOption === question.answer;
    const feedbackDiv = this.feedbackArea.createDiv(
      `csv-quiz-feedback-text ${isCorrect ? "csv-quiz-correct" : "csv-quiz-incorrect"}`
    );
    feedbackDiv.createEl("strong", {
      text: isCorrect ? "\u2713 \u6B63\u786E!" : "\u2717 \u9519\u8BEF!"
    });
    if (!isCorrect) {
      feedbackDiv.createEl("span", {
        text: ` \u6B63\u786E\u7B54\u6848: ${correctDisplayLetter}`
      });
    }
  }
  renderCheckboxArea(question) {
    this.checkboxArea.empty();
    const fields = [
      { key: "favorite", label: "\u6536\u85CF", value: question.favorite },
      { key: "mastered", label: "\u638C\u63E1", value: question.mastered },
      { key: "repeat", label: "\u91CD\u590D", value: question.repeat },
      { key: "wrong", label: "\u9519\u9898", value: question.wrong }
    ];
    for (const f of fields) {
      const labelEl = this.checkboxArea.createEl("label");
      const cb = labelEl.createEl("input", {
        type: "checkbox",
        attr: { "data-field": f.key }
      });
      cb.checked = f.value === "1";
      labelEl.createSpan({ text: " " + f.label });
      cb.addEventListener("change", () => {
        const q = question;
        q[f.key] = cb.checked ? "1" : "";
        void this.saveQuestionToCSV(question).then(() => {
          this.saveState();
        });
      });
    }
  }
  renderEditArea(question) {
    this.editArea.empty();
    const settings = this.getSettings();
    const toggleHeader = this.editArea.createDiv("csv-quiz-filter-toggle");
    const toggleIcon = toggleHeader.createSpan("csv-quiz-filter-icon");
    toggleHeader.createEl("span", { text: "\u6807\u7B7E / \u5206\u7C7B (\u7F16\u8F91\u540E\u81EA\u52A8\u4FDD\u5B58)" });
    const editBody = this.editArea.createDiv("csv-quiz-edit-grid");
    const panelOpen = settings.editPanelOpen;
    editBody.classList.toggle("csv-quiz-edit-grid-hidden", !panelOpen);
    toggleIcon.textContent = panelOpen ? "\u25BC" : "\u25B6";
    toggleHeader.addEventListener("click", () => {
      const isHidden = editBody.classList.contains("csv-quiz-edit-grid-hidden");
      editBody.classList.toggle("csv-quiz-edit-grid-hidden");
      toggleIcon.textContent = isHidden ? "\u25BC" : "\u25B6";
    });
    const tagRow = editBody.createDiv("csv-quiz-edit-row");
    tagRow.createEl("label", { text: "\u6807\u7B7E: ", cls: "csv-quiz-edit-label" });
    const tagInput = tagRow.createEl("input", {
      type: "text",
      cls: "csv-quiz-input csv-quiz-edit-input"
    });
    tagInput.value = question.tags;
    tagInput.dataset.field = "tags";
    const cat1Row = editBody.createDiv("csv-quiz-edit-row");
    cat1Row.createEl("label", {
      text: "\u4E00\u7EA7\u5206\u7C7B: ",
      cls: "csv-quiz-edit-label"
    });
    const cat1Input = cat1Row.createEl("input", {
      type: "text",
      cls: "csv-quiz-input csv-quiz-edit-input"
    });
    cat1Input.value = question.category1;
    cat1Input.dataset.field = "category1";
    const cat2Row = editBody.createDiv("csv-quiz-edit-row");
    cat2Row.createEl("label", {
      text: "\u4E8C\u7EA7\u5206\u7C7B: ",
      cls: "csv-quiz-edit-label"
    });
    const cat2Input = cat2Row.createEl("input", {
      type: "text",
      cls: "csv-quiz-input csv-quiz-edit-input"
    });
    cat2Input.value = question.category2;
    cat2Input.dataset.field = "category2";
    const cat3Row = editBody.createDiv("csv-quiz-edit-row");
    cat3Row.createEl("label", {
      text: "\u4E09\u7EA7\u5206\u7C7B: ",
      cls: "csv-quiz-edit-label"
    });
    const cat3Input = cat3Row.createEl("input", {
      type: "text",
      cls: "csv-quiz-input csv-quiz-edit-input"
    });
    cat3Input.value = question.category3;
    cat3Input.dataset.field = "category3";
    const saveBtn = editBody.createEl("button", {
      text: "\u4FDD\u5B58\u4FEE\u6539",
      cls: "csv-quiz-btn csv-quiz-btn-primary"
    });
    saveBtn.addEventListener("click", () => {
      void this.saveCurrentEdit();
    });
  }
  async handleAnswer(selectedKey) {
    if (this.answering || this.showingAnswer) return;
    this.answering = true;
    this.selectedOption = selectedKey;
    await this.saveCurrentEdit();
    const question = this.filteredQuestions[this.currentIndex];
    if (!question) {
      this.answering = false;
      return;
    }
    this.showingAnswer = true;
    this.answeredQuestions[question.id] = selectedKey;
    const isCorrect = selectedKey === question.answer;
    if (isCorrect) {
      this.correctCount++;
      this.renderQuestion();
      const settings = this.getSettings();
      if (settings.autoNextDelay > 0) {
        this.autoNextTimer = window.setTimeout(() => {
          void this.nextQuestion();
        }, settings.autoNextDelay * 1e3);
      } else {
        this.answering = false;
      }
    } else {
      this.wrongCount++;
      if (question.wrong !== "1") {
        question.wrong = "1";
        await this.saveQuestionToCSV(question);
      }
      this.renderQuestion();
      this.answering = false;
    }
    this.updateProgress();
    this.saveState();
  }
  cancelAutoNext() {
    if (this.autoNextTimer !== null) {
      window.clearTimeout(this.autoNextTimer);
      this.autoNextTimer = null;
    }
  }
  async nextQuestion() {
    var _a;
    await this.saveCurrentEdit();
    const origId = (_a = this.filteredQuestions[this.currentIndex]) == null ? void 0 : _a.id;
    this.reFilterForNavigation();
    if (!origId) return;
    const found = this.filteredQuestions.some((q) => q.id === origId);
    if (found) {
      const newIdx = this.filteredQuestions.findIndex((q) => q.id === origId);
      if (newIdx < this.filteredQuestions.length - 1) {
        this.currentIndex = newIdx + 1;
      } else {
        this.currentIndex = newIdx;
        return;
      }
    }
    this.currentShuffledQId = null;
    this.cancelAutoNext();
    this.renderQuestion();
    this.saveState();
  }
  async prevQuestion() {
    var _a;
    await this.saveCurrentEdit();
    const origId = (_a = this.filteredQuestions[this.currentIndex]) == null ? void 0 : _a.id;
    this.reFilterForNavigation();
    if (!origId) return;
    const found = this.filteredQuestions.some((q) => q.id === origId);
    if (found) {
      const newIdx = this.filteredQuestions.findIndex((q) => q.id === origId);
      if (newIdx > 0) {
        this.currentIndex = newIdx - 1;
      } else {
        return;
      }
    } else {
      if (this.currentIndex > 0) {
        this.currentIndex--;
      } else {
        return;
      }
    }
    this.currentShuffledQId = null;
    this.cancelAutoNext();
    this.renderQuestion();
    this.saveState();
  }
  updateNavigation() {
    var _a;
    this.navigationArea.empty();
    const navInner = this.navigationArea.createDiv("csv-quiz-nav-inner");
    const prevBtn = navInner.createEl("button", {
      text: "\u25C0 \u4E0A\u4E00\u9898",
      cls: "csv-quiz-btn"
    });
    prevBtn.disabled = this.currentIndex <= 0;
    prevBtn.addEventListener("click", () => {
      void this.prevQuestion();
    });
    const jumpGroup = navInner.createDiv("csv-quiz-nav-jump");
    jumpGroup.createEl("label", { text: "\u7B2C " });
    const jumpInput = jumpGroup.createEl("input", {
      type: "text",
      placeholder: "\u4F4D\u7F6E",
      cls: "csv-quiz-input csv-quiz-jump-input"
    });
    jumpGroup.createEl("label", { text: " / " + this.filteredQuestions.length + " \u9898 " });
    const jumpBtn = jumpGroup.createEl("button", {
      text: "\u8DF3\u8F6C",
      cls: "csv-quiz-btn"
    });
    jumpBtn.addEventListener("click", () => {
      void (async () => {
        await this.saveCurrentEdit();
        const targetStr = jumpInput.value.trim();
        if (!targetStr) return;
        const targetNum = parseInt(targetStr, 10);
        if (isNaN(targetNum) || targetNum < 1 || targetNum > this.filteredQuestions.length) {
          new import_obsidian3.Notice("\u9898\u53F7\u4E0D\u5B58\u5728\u6216\u5DF2\u88AB\u7B5B\u9009");
          return;
        }
        this.currentIndex = targetNum - 1;
        this.currentShuffledQId = null;
        this.cancelAutoNext();
        this.renderQuestion();
        this.saveState();
      })();
    });
    const nextBtn = navInner.createEl("button", {
      text: "\u4E0B\u4E00\u9898 \u25B6",
      cls: "csv-quiz-btn"
    });
    nextBtn.disabled = this.currentIndex >= this.filteredQuestions.length - 1;
    nextBtn.addEventListener("click", () => {
      void this.nextQuestion();
    });
    this.bottomBar.empty();
    const bottomRow = this.bottomBar.createDiv("csv-quiz-bottom-row");
    const nextUnansweredBtn = bottomRow.createEl("button", {
      text: "\u4E0B\u4E00\u4E2A\u672A\u7B54\u9898",
      cls: "csv-quiz-btn csv-quiz-btn-sm"
    });
    nextUnansweredBtn.addEventListener("click", () => this.goToNextUnanswered());
    const qId = (_a = this.filteredQuestions[this.currentIndex]) == null ? void 0 : _a.id;
    bottomRow.createEl("span", {
      text: qId ? `\u9898\u53F7: ${qId}` : "",
      cls: "csv-quiz-q-id-bottom"
    });
  }
  goToNextUnanswered() {
    if (this.filteredQuestions.length === 0) return;
    for (let i = this.currentIndex + 1; i < this.filteredQuestions.length; i++) {
      if (!this.answeredQuestions[this.filteredQuestions[i].id]) {
        this.currentIndex = i;
        this.currentShuffledQId = null;
        this.cancelAutoNext();
        this.renderQuestion();
        this.saveState();
        return;
      }
    }
    new import_obsidian3.Notice("\u6CA1\u6709\u66F4\u591A\u672A\u7B54\u9898");
  }
  updateProgress() {
    const total = this.filteredQuestions.length;
    const current = total > 0 && this.currentIndex >= 0 ? this.currentIndex + 1 : 0;
    this.progressEl.textContent = `\u8FDB\u5EA6: ${current}/${total}`;
    this.statsEl.textContent = `\u2705 ${this.correctCount}  \u274C ${this.wrongCount}`;
    const totalAnswered = this.correctCount + this.wrongCount;
    if (totalAnswered > 0) {
      const rate = (this.correctCount / totalAnswered * 100).toFixed(1);
      this.statsEl.textContent += `  (${rate}%)`;
    }
  }
  async saveCurrentEdit() {
    if (this.filteredQuestions.length === 0 || this.currentIndex < 0) return;
    const question = this.filteredQuestions[this.currentIndex];
    const previousId = question.id;
    const editInputs = Array.from(
      this.editArea.querySelectorAll(".csv-quiz-edit-input")
    );
    let changed = false;
    const q = question;
    for (const input of editInputs) {
      const field = input.dataset.field;
      if (!field) continue;
      const value = input.value;
      if (q[field] !== value) {
        q[field] = value;
        changed = true;
      }
    }
    if (changed) {
      await this.saveQuestionToCSV(question);
      this.filteredQuestions = filterQuestions(
        this.orderedQuestions,
        this.filterTags,
        this.filterCat1,
        this.filterCat2,
        this.filterCat3,
        this.filterFavorite,
        this.filterMastered,
        this.filterRepeat,
        this.filterWrong
      );
      const newIndex = this.filteredQuestions.findIndex(
        (q2) => q2.id === previousId
      );
      if (newIndex >= 0) {
        this.currentIndex = newIndex;
      } else if (this.filteredQuestions.length > 0) {
        this.currentIndex = 0;
      } else {
        this.currentIndex = -1;
      }
      this.saveState();
      new import_obsidian3.Notice("\u4FEE\u6539\u5DF2\u4FDD\u5B58");
    }
  }
  async saveQuestionToCSV(question) {
    const newRow = generateCSVRow(question);
    try {
      await this.csvWriteQueue.enqueue(this.csvPath, (csvContent) => {
        const updatedContent = findAndUpdateRow(csvContent, question.id, newRow);
        if (updatedContent === null) {
          throw new Error("CSV \u4E2D\u672A\u627E\u5230\u5BF9\u5E94\u9898\u53F7");
        }
        return updatedContent;
      });
    } catch (e) {
      console.error("CSV Quiz: Failed to save question to CSV", e);
      if (e instanceof Error && e.message === "CSV \u4E2D\u672A\u627E\u5230\u5BF9\u5E94\u9898\u53F7") {
        new import_obsidian3.Notice("CSV \u4E2D\u672A\u627E\u5230\u5BF9\u5E94\u9898\u53F7\uFF0C\u4FEE\u6539\u672A\u4FDD\u5B58");
      } else {
        new import_obsidian3.Notice(`\u4FDD\u5B58\u5230 CSV \u5931\u8D25: ${e instanceof Error ? e.message : String(e)}`);
      }
    }
  }
  async refresh() {
    await this.saveCurrentEdit();
    this.cancelAutoNext();
    if (this.autoSaveTimer !== null) {
      window.clearInterval(this.autoSaveTimer);
      this.autoSaveTimer = null;
    }
    const settings = this.getSettings();
    this.csvPath = settings.csvPath;
    try {
      const csvContent = await readCSVFile(this.vault, this.csvPath);
      this.allQuestions = parseCSV(csvContent);
      await this.stateManager.clearState();
      this.displayOrder = buildDisplayOrder(
        this.allQuestions,
        settings.randomOrder
      );
      this.orderedQuestions = sortByDisplayOrder(
        this.allQuestions,
        this.displayOrder
      );
      this.filterTags = "";
      this.filterCat1 = "";
      this.filterCat2 = "";
      this.filterCat3 = "";
      this.filterFavorite = settings.defaultFilterFavorite;
      this.filterMastered = settings.defaultFilterMastered;
      this.filterRepeat = settings.defaultFilterRepeat;
      this.filterWrong = settings.defaultFilterWrong;
      this.filteredQuestions = filterQuestions(
        this.orderedQuestions,
        this.filterTags,
        this.filterCat1,
        this.filterCat2,
        this.filterCat3,
        this.filterFavorite,
        this.filterMastered,
        this.filterRepeat,
        this.filterWrong
      );
      this.currentIndex = 0;
      this.correctCount = 0;
      this.wrongCount = 0;
      this.answeredQuestions = {};
      this.currentShuffledQId = null;
      this.updateFilterUI();
      this.renderQuestion();
      this.saveState();
      this.startAutoSave();
      new import_obsidian3.Notice("\u5DF2\u5237\u65B0\uFF0C\u91CD\u65B0\u5F00\u59CB");
    } catch (e) {
      console.error("CSV Quiz: Refresh failed", e);
      this.showError(`\u5237\u65B0\u5931\u8D25: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  showError(message) {
    this.questionArea.empty();
    this.questionArea.createEl("p", {
      text: message,
      cls: "csv-quiz-error"
    });
  }
  getSettings() {
    return this.plugin.settings;
  }
  buildCurrentState() {
    return {
      csvPath: this.csvPath,
      currentIndex: this.currentIndex,
      correctCount: this.correctCount,
      wrongCount: this.wrongCount,
      displayOrder: this.displayOrder,
      filterTags: this.filterTags,
      filterCat1: this.filterCat1,
      filterCat2: this.filterCat2,
      filterCat3: this.filterCat3,
      filterFavorite: this.filterFavorite,
      filterMastered: this.filterMastered,
      filterRepeat: this.filterRepeat,
      filterWrong: this.filterWrong,
      answeredQuestions: this.answeredQuestions
    };
  }
  saveState() {
    const state = this.buildCurrentState();
    this.stateManager.scheduleSave(state, 300);
  }
};

// src/stateManager.ts
var StateWriteQueue = class {
  constructor(plugin) {
    this.queue = [];
    this.processing = false;
    this.plugin = plugin;
  }
  enqueue(patch) {
    return new Promise((resolve, reject) => {
      this.queue.push({ patch, resolve, reject });
      void this.processNext();
    });
  }
  async processNext() {
    if (this.processing || this.queue.length === 0) return;
    this.processing = true;
    const item = this.queue.shift();
    try {
      const data = await this.plugin.loadData() || {};
      if (item.patch.settings !== void 0) {
        data.settings = item.patch.settings;
      }
      if (item.patch.quizState !== void 0) {
        data.quizState = item.patch.quizState;
      }
      await this.plugin.saveData(data);
      item.resolve();
    } catch (e) {
      item.reject(e);
    } finally {
      this.processing = false;
      void this.processNext();
    }
  }
  get pending() {
    return this.queue.length;
  }
};
var StateManager = class {
  constructor(plugin) {
    this.currentState = null;
    this.saveTimer = null;
    this.plugin = plugin;
    this.writeQueue = new StateWriteQueue(plugin);
  }
  async loadPluginData(currentSettings) {
    const data = await this.plugin.loadData() || {};
    const settings = {
      ...currentSettings,
      ...data.settings || {}
    };
    const quizState = data.quizState ? { ...data.quizState } : null;
    this.currentState = quizState;
    return { settings, quizState };
  }
  getState() {
    return this.currentState;
  }
  setState(state) {
    this.currentState = state;
  }
  async saveStateImmediately(state) {
    this.currentState = state;
    await this.writeQueue.enqueue({ quizState: state });
  }
  scheduleSave(state, delay = 300) {
    this.currentState = state;
    if (this.saveTimer !== null) {
      window.clearTimeout(this.saveTimer);
    }
    this.saveTimer = window.setTimeout(() => {
      this.saveTimer = null;
      this.writeQueue.enqueue({ quizState: state }).catch(
        (e) => console.error("CSV Quiz: Failed to save state", e)
      );
    }, delay);
  }
  async clearState() {
    this.currentState = null;
    await this.writeQueue.enqueue({ quizState: null });
  }
  cancelScheduledSave() {
    if (this.saveTimer !== null) {
      window.clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
  }
  async saveSettings(settings) {
    await this.writeQueue.enqueue({ settings });
  }
};

// src/main.ts
var CSVQuizPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    this.stateManager = new StateManager(this);
    this.csvWriteQueue = new CSVWriteQueue(this.app.vault);
    await this.loadSettings();
    await this.stateManager.loadPluginData(this.settings);
    this.registerView(VIEW_TYPE_QUIZ, (leaf) => {
      const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_QUIZ);
      if (existing.length > 0 && existing[0] !== leaf) {
        leaf.detach();
        this.app.workspace.setActiveLeaf(existing[0], false, true);
        return new QuizView(leaf, this, this.stateManager, this.app.vault, this.csvWriteQueue);
      }
      return new QuizView(leaf, this, this.stateManager, this.app.vault, this.csvWriteQueue);
    });
    this.addRibbonIcon("book-open", "\u5237\u9898\u554A", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-quiz-practice",
      name: "\u6253\u5F00\u5237\u9898\u9762\u677F",
      callback: () => {
        void this.activateView();
      }
    });
    this.addSettingTab(new CSVQuizSettingTab(this.app, this));
  }
  onunload() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_QUIZ);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && view.onClose) {
        void view.onClose();
      }
    }
  }
  activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_QUIZ).first();
    if (!leaf) {
      leaf = workspace.getLeaf(true);
      void leaf.setViewState({ type: VIEW_TYPE_QUIZ, active: true });
    }
    workspace.setActiveLeaf(leaf, false, true);
  }
  refreshQuiz() {
    const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_QUIZ).first();
    if (leaf) {
      const view = leaf.view;
      void view.refresh();
    }
  }
  async loadSettings() {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i;
    const data = await this.loadData() || {
      settings: {
        csvPath: "\u9898\u5E93.csv",
        randomOrder: false,
        randomOptions: false,
        autoNextDelay: 1,
        filterPanelOpen: true,
        editPanelOpen: true
      },
      quizState: null
    };
    this.settings = {
      csvPath: data.settings.csvPath || "\u9898\u5E93.csv",
      randomOrder: (_a = data.settings.randomOrder) != null ? _a : false,
      randomOptions: (_b = data.settings.randomOptions) != null ? _b : false,
      autoNextDelay: (_c = data.settings.autoNextDelay) != null ? _c : 1,
      filterPanelOpen: (_d = data.settings.filterPanelOpen) != null ? _d : true,
      editPanelOpen: (_e = data.settings.editPanelOpen) != null ? _e : true,
      defaultFilterFavorite: (_f = data.settings.defaultFilterFavorite) != null ? _f : "",
      defaultFilterMastered: (_g = data.settings.defaultFilterMastered) != null ? _g : "",
      defaultFilterRepeat: (_h = data.settings.defaultFilterRepeat) != null ? _h : "",
      defaultFilterWrong: (_i = data.settings.defaultFilterWrong) != null ? _i : ""
    };
  }
  async saveSettings() {
    await this.stateManager.saveSettings(this.settings);
  }
};
/*! Bundled license information:

papaparse/papaparse.min.js:
  (* @license
  Papa Parse
  v5.5.4
  https://github.com/mholt/PapaParse
  License: MIT
  *)
*/
